-- Seed: Plano de Históricos SCI (Anexo 2 - Plano de historicos contabeis do SCI.csv)
-- 560 códigos oficiais. Reexecutável (ON CONFLICT DO UPDATE).

INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (19, 'AQUISINVEST', 'Aquisição de investimento', false),
  (35, 'BX IMOB', 'Baixa de imobilizado', false),
  (43, 'CHQCOMPENS', 'Cheque compensado', false),
  (51, 'CHQNR', 'Cheque nº', false),
  (78, 'COBRDUPLIC', 'Cobrança de duplicatas', false),
  (86, 'COFINS', 'Cofins ref. mês', false),
  (357, NULL, 'Custo do mês', false),
  (108, 'IMO', 'Compra de bens do ativo imobilizado ref.', false),
  (132, 'CPR', 'Compras ref. *M', false),
  (140, 'DEBITBANC', 'Débito bancário ref.:', false),
  (159, 'TARIFABANC', 'Débito tarifa bancária cfe. extrato', true),
  (175, 'DEPRE', 'Depreciação do mês *M', false),
  (1058, '363', 'Apropriação IRPJ do período', false),
  (1066, '269', 'Apropriação CSLL do período', false),
  (1074, '267', 'Apropriação cofins do período', false),
  (2712, 'APLICA', 'Aplicação CAIXA', false),
  (27, NULL, 'Integralização de capital do(a) sócio(a):', false),
  (3611, NULL, 'Credito Cielo', false),
  (47, NULL, 'ISQN em', false),
  (207, NULL, 'Lucros e perdas', false),
  (257, NULL, 'Pagamento de honorários', false),
  (287, NULL, 'Juros sobre aplicação financeira', false),
  (297, NULL, 'Serviços prestados ref. NF', false),
  (477, NULL, 'Recebimento de clientes', false),
  (567, NULL, 'Provisões de', false),
  (568, NULL, 'Saldo de caixa do exercício anterior', false),
  (574, 'DVLV', 'Devoluções', false),
  (590, NULL, 'Amortização período', false),
  (1325, '421', 'Venda de produtos a prazo conf.', false),
  (1333, '422', 'Venda de mercadorias a prazo conf.', false),
  (1830, NULL, 'Crédito conforme extrato', false),
  (1856, NULL, 'Lucro apurado no período', false),
  (1872, NULL, 'Prejuízo apurado no período', false),
  (1880, NULL, 'PIS sobre provisão aluguel', false),
  (1899, NULL, 'Cofins sobre provisão de aluguel', false),
  (1902, NULL, 'CSLL sobre provisão de aluguel', false),
  (1910, NULL, 'IRPJ sobre provisão de aluguel', false),
  (1929, NULL, 'Reversão de provisão PIS', false),
  (1961, NULL, 'Rendimento de aplicação financeira ref. mês.', false),
  (1970, NULL, 'IRPJ sobre aluguel recebido', false),
  (1988, NULL, 'CSLL sobre aluguéis recebidos', false),
  (2089, NULL, 'Pagamento de cartão de crédito ref.', false),
  (2127, 'DVICMS', 'ICMS sobre devolução', false),
  (2240, 'AJUST', 'Ajuste ref.:', false),
  (2259, 'DESCCONC', 'Desconto concedido ref.:', false),
  (2275, 'BADINT', 'Baixa de adiantamento de clientes', false),
  (2291, 'COF', 'Cofins a pagar ref.:', false),
  (2305, 'ALUGPG', 'Aluguel a pagar ref. mês:', false),
  (2330, 'PAGENERGIA', 'Pagamento de energia elétrica ref.', false),
  (2402, 'VVEICULOS', 'Venda do ativo imobilizado', false),
  (2437, 'REFFINAN', 'Conforme contrato de financiamento n°:', false),
  (2453, 'AUMCAP', 'Aumento de capital', false),
  (2461, 'MULTAICMS', 'Multa ref. auto de infração nº', false),
  (2470, 'ADIANTFOR', 'Adiantamento a fornecedores ref.:', false),
  (2518, 'RRVA', 'Reavaliação ref.:', false),
  (2526, 'APRDESP', 'Apropriação de despesas ref.:', false),
  (2577, 'SERVTO', 'Serviços tomados ref. NF', false),
  (2682, 'ADIANTAMENTO', 'Adiantamento de aluguel ref.:', false),
  (2720, 'RECEITAF', 'Receita de Aplic. financeira ref.:', false),
  (2739, 'IRPJEST', 'IRPJ por estimativa ref. mês:', false),
  (2747, 'CSLLEST', 'CSLL por estimativa ref. mês:', false),
  (2780, 'DEB', 'Débito de ICMS ref.:', false),
  (3018, NULL, 'Implantação de saldo', true),
  (3050, 'CP', 'Compras cfe NF nº.', false),
  (3182, NULL, 'IOF a recolher ref. contrato de', false),
  (3247, NULL, 'Devolução de vendas conf. NF nº.', false),
  (3549, 'DB', 'Débito', false),
  (3557, NULL, 'Dividendos recebidos', false),
  (3565, 'DEP', 'Depósito', false),
  (3590, 'DF', 'Débito fatura', false),
  (3646, 'CD', 'Estorno cheque depositado devolvido', false),
  (213, 'DUPLICDESCBANC', 'Duplicatas descontas no banco', false),
  (221, 'EMPREST', 'Empréstimo', false),
  (264, 'ENCERR', 'Encerramento do exercício', false),
  (280, 'ESTORNO', 'Estorno', false),
  (329, 'ICMSRECUP', 'ICMS a recuperar ref.:', false),
  (345, 'ICMSSVENDAS', 'ICMS sobre vendas', false),
  (418, 'JUROSEMPRBANC', 'Juros sobre empréstimos bancários', false),
  (2, NULL, 'Encerramento no trimestre', false),
  (6, NULL, 'Saldo de abertura', false),
  (834, 'DEPRETRI', 'Depreciação do trimestre', false),
  (3663, 'COMPENER', 'Compras energia elétrica conf. NF nº.', false),
  (3664, 'CREDITO', 'Cartão de crédito', false),
  (1, NULL, 'Valor ref. saldo abertura cfe levantamento', false),
  (4, NULL, 'Valor ref. abastecimento CTF', true),
  (5, NULL, 'Valor venda a prazo cfe CFe nº', false),
  (7, NULL, 'Valor ref. pagamento férias', false),
  (8, NULL, 'Valor ref. saque c/c com cartão', true),
  (9, NULL, 'Valor ref. pagamento cheque devolvido - cfe depósito c/c', true),
  (10, NULL, 'Valor ref. pagamento fatura nº', false),
  (20, 'Com', 'Compras em', false),
  (21, 'SERVIÇOS', 'Serviços de industrialização cfe NF nº', false),
  (29, NULL, 'Vendas cfe NF nº', false),
  (30, 'Ven', 'Vendas em', false),
  (31, NULL, 'Valor ref. recebimento fatura nº', false),
  (32, NULL, 'Valor ref. recebimento CF nº', false),
  (34, NULL, 'Valor ref. recebimento NF nº', false),
  (37, NULL, 'NF nº', false),
  (40, NULL, 'PIS ref.:', false),
  (50, NULL, 'ICMS em', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;

INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (60, NULL, 'IPI em', false),
  (70, NULL, 'ISS em', false),
  (77, NULL, 'Pró-labore * - *', false),
  (84, NULL, 'Valor revenda de mercadoria cfe reduçao Z nº', false),
  (85, NULL, 'Valor revenda de mercadoria cfe NF nº', false),
  (87, 'INSS', 'INSS em', false),
  (94, 'COMISS', 'Comissões', false),
  (97, NULL, 'Honorários', false),
  (107, NULL, 'IR sobre honorários', false),
  (117, NULL, 'Saídas em', false),
  (147, NULL, 'Pagamento de combustíveis', false),
  (157, NULL, 'Pagamento de hospedagens', false),
  (167, NULL, 'Pagamento almoço/jantar', false),
  (177, NULL, 'Conversão de Cr$ para CR$', false),
  (183, 'DESCINSSFOLHA', 'Desconto INSS s/ folha de pgto', false),
  (187, NULL, 'Saldo convertido em CR$', false),
  (191, 'DVLC', 'Devolução de compras conf. NF nº', false),
  (197, NULL, 'Transferência para lucros e perdas', false),
  (227, NULL, 'Folha de pagamento', false),
  (230, 'EMPRLIG', 'Empréstimo a empresa ligada', false),
  (237, 'FGTS', 'FGTS', false),
  (247, NULL, 'Pagamento IR sobre honorários', false),
  (248, 'EMPRESBANC', 'Empréstimo bancário', false),
  (256, 'EMPRESTSOCIO', 'Empréstimo de sócio ref.', false),
  (267, NULL, 'Pagamento de salários ref.:', false),
  (272, 'ENTRADASEM', 'Entradas em', false),
  (307, NULL, 'Pagamento de * de *', false),
  (317, NULL, 'Pagamento NF nº', false),
  (367, NULL, 'Depósito ref.:', false),
  (370, 'IPIRECUP', 'IPI a recuperar ref.:', false),
  (427, NULL, 'Pagamento de INSS ref.:', false),
  (437, NULL, 'Pagamento de FGTS ref.:', false),
  (442, 'PGTOCOFINS', 'Pagamento de cofins ref.:', false),
  (447, NULL, 'Pagamento de PIS ref.:', false),
  (450, NULL, 'Valor ref. recebimento vales', false),
  (451, NULL, 'Valor ref. recebimento ordem frete cliente', false),
  (460, NULL, 'Valor ref. emissão de vale', false),
  (467, NULL, 'Pagamento ISQN ref.:', false),
  (478, NULL, 'Recebimento de clientes cfe NF nº', false),
  (497, NULL, 'Pagamento de pró-labore ref.:', false),
  (507, NULL, 'Conversão de CR$ para R$', false),
  (517, NULL, 'Saldo convertido em R$', false),
  (531, 'PGTOJUROSDUPL', 'Pagamento juros sobre duplicata', false),
  (537, NULL, 'Pagamento de duplicata * fornec. *D', false),
  (582, NULL, 'Depreciação do período', false),
  (604, '65', 'Empréstimos a funcionários', false),
  (612, '164', 'Aviso prévio não cumprido e art. 479', false),
  (620, '165', 'Desconto ligações telefônicas', false),
  (639, '193', 'IRRF sobre férias', false),
  (647, '201', 'Contr. sindical a pagar', false),
  (655, '203', 'INSS descontado sobre férias', false),
  (663, '204', 'Salário família ref.:', false),
  (671, '206', 'Folha de pagamento a pagar', false),
  (680, '214', 'Pró-labore a pagar', false),
  (701, 'COMVEN', 'Comissões sobre vendas', false),
  (710, NULL, 'Valor depósito no dia', true),
  (728, '236', 'Pagamento de saldo de salário', false),
  (736, '275', 'Desconto empréstimo concedido', false),
  (744, '280', 'IRRF sobre adiantamento de salário', false),
  (752, '281', 'Provisão de férias ref.:', false),
  (760, '283', 'Provisão de 13º salário ref.:', false),
  (779, '284', 'Reversão da provisão de 13º salário ref. período anterior', false),
  (780, 'SEC', 'Valor serviços cfe ECF nº', false),
  (787, '287', 'Reversão da provisão de férias ref. período anterior', false),
  (795, '285', 'Pagamento bolsa auxílio', false),
  (796, NULL, 'Valor desconto sobre', false),
  (800, NULL, 'Valor pago a maior NFe nº.', false),
  (801, NULL, 'Valor pago a maior ECF nº.', false),
  (809, '366', 'Desconto vale transporte', false),
  (810, NULL, 'Valor emissão de cheque nº', false),
  (811, NULL, 'Valor IOF a débito de c/c', false),
  (812, NULL, 'Valor pagamento de juros', false),
  (813, NULL, 'Valor pagamento título nº', false),
  (814, NULL, 'Pagamento cfe recibo', false),
  (817, '367', 'Desconto cesta básica', false),
  (825, '368', 'Desconto vale refeição', false),
  (833, '370', 'FGTS s/ 13º. salário', false),
  (841, '382', 'Ref. 13º salário', false),
  (850, '383', 'IRRF sobre 13º salário', false),
  (868, '440', 'Desconto assist. médica', false),
  (884, '477', 'Contribuição INSS do mês', false),
  (906, '479', 'Desconto adto sobre salário do mês', false),
  (914, '480', 'IRRF sobre folha', false),
  (922, '482', 'INSS sobre folha ref.:', false),
  (930, '483', 'INSS descontado sobre 13º. salário', false),
  (949, '485', 'Férias no mês', false),
  (957, '491', 'Pensão judicial a pagar ref.:', false),
  (965, '493', 'Desconto líquido rescisão', false),
  (973, '611', 'Ref. gratificações', false),
  (981, '621', 'Arredondamento salário conf. folha', false),
  (990, '693', 'Bolsa auxílio no mês conf. folha', false),
  (999, NULL, 'Pagamento NF * - *D', false),
  (1000, 'PGTO', 'Pagamento *D ref. *N', false),
  (1001, NULL, 'Pagamento de', false),
  (1002, NULL, 'Débito ref.', false),
  (1005, NULL, 'Crédito ref.', false),
  (1006, NULL, 'Valor ref.:', false),
  (1007, '202', 'Desconto contribuição assistencial', false),
  (1015, '257', 'Desconto contribuição sindical', false),
  (1023, '273', 'Salário maternidade ref.:', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;

INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (1031, '384', 'Desconto 13º. salário', false),
  (1040, '385', 'Distribuição de lucros', false),
  (1082, '90', 'Apropriação fretes e carretos', false),
  (1090, '313', 'ISS a recolher', false),
  (1104, 'ICMSVDAS', 'ICMS devido sobre vendas do mês', false),
  (1112, '316', 'ICMS crédito sobre compras', false),
  (1120, '317', 'ICMS débito sobre transferência', false),
  (1139, '318', 'ICMS crédito sobre transferência', false),
  (1147, '319', 'ICMS débito sobre devolução compras', false),
  (1155, '320', 'ICMS crédito sobre devolução vendas', false),
  (1163, '321', 'IPI débito sobre vendas', false),
  (1171, '322', 'IPI crédito sobre compras', false),
  (1180, '323', 'IPI débito sobre transferência', false),
  (1198, '324', 'IPI crédito sobre transferência', false),
  (1201, '325', 'IPI débito sobre devolução compras', false),
  (1210, '326', 'IPI crédito sobre devolução vendas', false),
  (1228, '328', 'ICMS recuperado ref.:', false),
  (1236, '329', 'IPI recuperado ref.:', false),
  (1260, '339', 'Apropriação PIS do período', false),
  (1279, '374', 'Material de escritório conf. NF nº', false),
  (1287, '397', 'Material de limpeza a prazo', false),
  (1295, '399', 'Material de escritório a prazo', false),
  (1309, '400', 'Material de consumo a prazo', false),
  (1317, '419', 'Venda a prazo cfe NF nº', false),
  (1341, '424', 'Serviços prestados a prazo ref.:', false),
  (1368, '430', 'ICMS sobre conta de luz', false),
  (1376, '432', 'Despesas com cesta básica', false),
  (1384, '434', 'Bens do permanente a prazo conf. reg.', false),
  (1392, '436', 'Uniformes a prazo conf.', false),
  (1406, '437', 'Serviços gráficos a prazo ref.:', false),
  (1414, '438', 'ICMS do mês', false),
  (1422, '458', 'Compras de merc. a prazo no mês conf.', false),
  (1430, '459', 'Despesas com brindes a prazo conf.', false),
  (1449, '462', 'ICMS sobre matéria prima', false),
  (1457, '463', 'IPI sobre venda de produtos', false),
  (1465, '464', 'ICMS sobre compras de brindes', false),
  (1473, '465', 'ICMS sobre beneficiamento', false),
  (1481, '468', 'IPI sobre matéria prima', false),
  (1490, '469', 'IPI sobre beneficiamento', false),
  (1503, '470', 'IPI sobre matéria prima devolvida', false),
  (1511, '471', 'ICMS sobre matéria prima devolvida', false),
  (1520, '472', 'IPI sobre venda de mercadorias', false),
  (1538, '501', 'Compras vista matéria prima conf.', false),
  (1546, '503', 'Compras a vista embalagens conf.', false),
  (1554, '504', 'Compras a vista mercadorias conf.', false),
  (1562, '505', 'Compras vista produtos comb. conf.', false),
  (1570, '520', 'Apropriação amostras grátis', false),
  (1589, '531', 'Compras prazo matéria prima conf.', false),
  (1597, '532', 'Compras prazo mat. sec. conf.', false),
  (1600, '533', 'Compras prazo embalagens conf.', false),
  (1619, '534', 'Compras prazo mercadorias conf.', false),
  (1627, '544', 'Despesa com veículos a prazo conf. NF nº', false),
  (1635, '548', 'Conserto e reparos a prazo no mês conf.', false),
  (1643, '656', 'Pagamento Conta de Telefone no mês', false),
  (1660, '720', 'Entrada de licença de uso', false),
  (1678, '721', 'Saída de licença de uso', false),
  (1686, '724', 'Remessa e/ou devolução conserto', false),
  (1694, '725', 'Entrada e/ou retorno conserto', false),
  (1708, '726', 'Outros débitos (frete) conf. art. 103 RICMS', false),
  (1716, '727', 'Entrada de demonstração', false),
  (1724, '729', 'ICMS sobre cesta básica', false),
  (1732, '730', 'ICMS diversos', false),
  (1740, '733', 'Desconto concedido sobre NF', false),
  (1759, '735', 'Desconto concedido sobre duplicata', false),
  (1767, '741', 'Pagamento de juros ref.', false),
  (1775, '752', 'Remessa e/ou devolução empréstimo', false),
  (1783, '753', 'Retorno e/ou recebimento de empréstimo', false),
  (1791, '805', 'Remessa e/ou retorno de beneficiamento', false),
  (1805, '410', 'IRRF sobre serviços prestados', false),
  (1813, NULL, 'Tarifa bancária', false),
  (1848, NULL, 'Transferência de imóveis com açoes IGW para JRA', false),
  (1864, NULL, 'Venda ref.:', false),
  (1937, NULL, 'Reversão de provisão COFINS', false),
  (1945, NULL, 'Reversão de provisão CSLL', false),
  (1953, NULL, 'Reversão de provisão IRPJ', false),
  (1996, NULL, 'Líquido de férias', false),
  (2000, 'RECEB', 'Recebimento *C ref. *N', false),
  (2003, NULL, 'ISS ref.:', false),
  (2011, NULL, 'IRRF sobre NF', false),
  (2020, '840', 'Transferência entre contas', false),
  (2054, NULL, 'Pagamento de IRRF s/ aplicação financeira ref.', false),
  (2063, NULL, 'Transferência para encerramento do exercício ref.:', false),
  (2070, NULL, 'Transferência entre contas para adeq. L. 11.638/07', false),
  (2097, 'IPIVDAS', 'IPI sobre vendas', false),
  (2119, NULL, 'Transferência entre contas ref. consolidação', false),
  (2135, 'DVIPI', 'IPI sobre devolução', false),
  (2178, 'ALIM', 'Gastos com Alimentação', false),
  (2186, 'PASSAGENS', 'Gastos com passagens', false),
  (2194, 'INSSPROL', 'INSS sobre pró-labore ref. mês:', false),
  (2208, 'INSSSAL', 'INSS sobre salários ref. mês:', false),
  (2216, 'VALETRANS', 'Pagamento de vale transportes', false),
  (2224, 'HONOPG', 'Honorários a pagar ref. mês:', false),
  (2232, 'TASIC', 'Tarifas bancárias ref.:', false),
  (2283, 'PIRRF', 'Pagamento de IRRF ref.:', false),
  (2313, 'SIMPLES NAC', 'Simples nacional ref. mês:', false),
  (2321, 'SIMPLES NAC P', 'Pagamento de simples nacional ref.:', false),
  (2348, 'CTRCREC', 'Frete a receber ref. CTRC n°:', false),
  (2356, 'CREDPRE', 'Crédito presumido ICMS ref.:', false),
  (2364, 'DESCFARM', 'Desconto farmácia ref. mês:', false),
  (2372, 'DESCSUSP', 'Desconto dias suspensão ref. mês:', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;
INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (2380, 'INDT', 'Indenização término de contrato antecipado ref.:', false),
  (2399, 'GRATIF', 'Gratificação ref. mês:', false),
  (2410, 'PGTOVEIC', 'Pagamento de aquisição de veículos', false),
  (2429, 'FINAN', 'Despesas ref. financiamento n°:', false),
  (2445, 'PGTOPAR', 'Pagamento de parcelamento', false),
  (2488, 'INSSAUX', 'INSS sobre auxílio maternidade', false),
  (2496, 'TCFA', 'Taxa controle fiscal e ambiental a pagar', false),
  (2500, 'PTCFA', 'Pagamento de taxa de contribuição fiscal ambiental', false),
  (2534, 'PENSAO', 'Pensão a pagar ref.:', false),
  (2542, 'PENSAOO', 'Pagamento de pensão ref.:', false),
  (2550, 'TRANSFER', 'Transferência do lançamento:', false),
  (2569, 'SERVTOMADO', 'Pagamento de serviços tomados ref. NF:', false),
  (2585, 'FRETE', 'Pagamento de Frete ref.', false),
  (2593, 'FRETEPAGAR', 'Frete ref. CTRC nº:', false),
  (2607, 'ENERGIA', 'Energia elétrica ref.:', false),
  (2615, 'TELEFONE', 'Fatura telefônica ref. NF nº:', false),
  (2623, 'PAGMULTA', 'Pagamento de multas ref.:', false),
  (2631, 'IPIPAGAR', 'IPI a pagar ref.:', false),
  (2640, 'PATIPI', 'Pagamento de IPI ref.:', false),
  (2658, 'DESC RESC', 'Desconto rescisão ref.:', false),
  (2666, 'LICEN', 'Pagamento de licenciamento ref.:', false),
  (2674, 'BAIXA', 'Baixa de venda de imobilizado ref. NF:', false),
  (2690, 'TRANSFC', 'Transferência de', false),
  (2704, 'RESULMENSAL', 'Resultado do exercício ref. mês:', false),
  (2763, 'FGTSCOMP', 'FGTS a compensar ref.:', false),
  (2771, 'CRED', 'Crédito de ICMS ref.:', false),
  (2798, 'IPI', 'Crédito de IPI ref.:', false),
  (2801, 'PEDAGIO', 'Pagamento de pedágio', false),
  (2810, 'ICMSPARC', 'Pagamento de ICMS ref.:', false),
  (2836, 'COMPLSAL', 'Complemento salarial ref.:', false),
  (2844, 'PGTORENAUTO', 'Pagamento de rendimentos autônomos ref.:', false),
  (2852, 'RENAUTOPGR', 'Rendimentos de autônomos a pagar ref.:', false),
  (2860, 'PGTOCOMPL', 'Pagamento complemento salarial ref.:', false),
  (2879, '13COMPL', '13° salário complementar ref.:', false),
  (2887, 'PGTO13COMPL', 'Pagamento 13° salário complementar ref.:', false),
  (2909, 'PGTODISTFUNC', 'Pagamento de distribuição de lucros a funcionários', false),
  (2917, 'PROVDISTADM', 'Provisão para distribuição de lucros ref.:', false),
  (2925, 'PGTODISTADM', 'Pagamento de distribuição de lucros ref.', false),
  (2933, 'INSSEMPREC', 'INSS patronal a recolher ref.:', false),
  (2941, 'INSSAUTREC', 'INSS autônomo a recolher ref.:', false),
  (2950, 'PROFGTSMR', 'FGTS multa rescisória a pagar ref.:', false),
  (2968, 'IRRFSAL', 'IRRF sobre salários a recolher ref.:', false),
  (2976, 'IRRFPROL', 'IRRF sobre pró-labore a recolher ref.:', false),
  (2984, 'IRRFAUT', 'IRRF autônomo a recolher ref.:', false),
  (2992, 'CONTRSINDPAT', 'Contr. sindical patronal a recolher ref.:', false),
  (3000, 'RECDPL', 'Valor recebimento duplicata nº', false),
  (3026, NULL, 'Pagamento de duplicatas nº', false),
  (3042, NULL, 'Recebimento de clientes diversos em crédito c/c', false),
  (3069, 'VAV', 'Valor venda a vista cfe red. Z nº', false),
  (3077, NULL, 'Valor venda a prazo cfe relatório de venda', true),
  (3085, 'S', 'Valor serviços cfe red. Z nº', false),
  (3093, NULL, 'Valor venda cartão de crédito', true),
  (3107, NULL, 'Valor transferência venda cartão crédito/débito', false),
  (3115, NULL, 'Valor transferência vales a clientes', false),
  (3123, NULL, 'Recebimento clientes cfe relação anexa', false),
  (3131, NULL, 'Valor crédito Mastercard-Fininvest', false),
  (3140, 'SERVIÇOS FATURIZAÇÃO', 'Valor serviços de faturizaçao ref NF nº', false),
  (3166, NULL, 'Valor ref. recebimento de títulos', false),
  (3174, NULL, 'Valor de deságio/juros contrato de', false),
  (3204, NULL, 'Valor transferência de mercadorias', false),
  (3220, NULL, 'Valor compensado ref. cheque nº', false),
  (3255, NULL, 'Valor pago CF nº.', false),
  (3263, NULL, 'Receita de doação em depósito c/c', false),
  (3271, NULL, 'Valor de depreciação anual', true),
  (3280, NULL, 'Valor recebido clientes carteira cfe relação', false),
  (3298, NULL, 'Valor de adiantamento salarial', false),
  (3301, NULL, 'Valor saque caixa', true),
  (3310, NULL, 'Valor recebido ref. vales', true),
  (3328, NULL, 'Valor venda cartão crédito/débito', true),
  (3336, NULL, 'Recebimento parcela cfe livro reg. dupl. nº', false),
  (3344, 'SER', 'Valor serviços cfe NF nº', false),
  (3352, NULL, 'Valor ref. pagamento NF de serviços nº', false),
  (3360, NULL, 'Valor transferência ordens de fretes', false),
  (3379, NULL, 'Valor recebido cfe ordens de frete', false),
  (3387, 'ECF', 'Valor ref. CF nº.', false),
  (3409, NULL, 'Serviços a vista cfe NF nº', true),
  (3417, NULL, 'Valor de adiantamento 13º salário', false),
  (3420, NULL, 'Valor ref. pagamento 1ª. parcela 13º salário', false),
  (3425, NULL, 'Valor ref. pagamento 2ª. parcela 13º salário', false),
  (3433, 'MEDIC', 'Exames médicos ref.:', false),
  (3441, NULL, 'Valor ref. pagamento NF cfe relação', true),
  (3442, 'PG', 'Pagamento *D ref. *N', false),
  (3450, NULL, 'Valor transferência entre as contas ref. venda', false),
  (3476, NULL, 'Valor ref. pagamento cfe borderô de cobrança nº', false),
  (3484, NULL, 'Valor ref. reembolso INSS sobre 13º salário', false),
  (3492, NULL, 'Valor retido IRF sobre 13º salário', false),
  (3506, NULL, 'Valor ref. NFe nº.', false),
  (3507, NULL, 'Valor ref. NF n°.', false),
  (3510, NULL, 'Valor ref. pagamento NFe nº', false),
  (3511, NULL, 'Valor ref. pagamento NF n°', false),
  (3514, 'IIPGR', 'Imposto importação a pagar ref.:', false),
  (3515, NULL, 'NF-e nº', false),
  (3522, NULL, 'Valor ref. recebimento cheque cfe contrato', false),
  (3530, NULL, 'Valor ref. recebimento duplicata cfe contrato', false),
  (3555, NULL, 'Valor ref. ICMS substituição tributária', false),
  (3573, NULL, 'Crédito Rede Master', false),
  (3581, NULL, 'Crédito Rede Shop', false),
  (3603, NULL, 'Crédito Sodexho', false),
  (3620, NULL, 'Crédito Visa Electron/Cielo', false),
  (3638, 'DT', 'Débito título', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;

INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (3662, 'PT', 'Pagamento título nº', false),
  (3665, 'Ref.', 'Ref.', false),
  (3666, 'alug rec', 'Alugueis a receber ref. mes', false),
  (3667, 'pis pg', 'Pis a Pagar ref.', false),
  (3668, 'Compis', 'Compensação de Pis ref.:', false),
  (3669, 'Compcof', 'Compensação de Cofins ref.:', false),
  (3670, NULL, 'Contribuição Previdênciaria ref.', false),
  (3671, 'Aplic', 'Aplicação financeira nesta data.', false),
  (3672, 'Resgate', 'Resgate aplicação financeira nesta data.', false),
  (3673, NULL, 'Adiantamento de clientes:', false),
  (3674, 'Apuração', 'Apuração do Resultado do Exercicio:', false),
  (3675, 'resultado', 'Resultado do Exercicio:', false),
  (3676, 'Direitos', 'Receita de Direitos Autorais n/ mês', false),
  (3677, 'ISSPG', 'Pagto ISSQN n/ mês', false),
  (3678, 'IRPJPG', 'Pagto IRPJ ref.', false),
  (3679, 'CSLLPG', 'Pagto CSLL ref.', false),
  (3680, 'Ajudadecusto', 'Ajuda de Custo', false),
  (3681, 'PagEmpsoc', 'Pagamento de Empréstimo ao Sócio', false),
  (3682, 'PagtoPisCofinscsll', 'Pagamento Pis, Cofins e CSLL ref. NF', false),
  (3683, 'pagtotfe', 'Pagamento TFE ref. Exercicio:', false),
  (3684, 'Tfeexe', 'TFE ref. Exercicio:', false),
  (3685, 'PagCond', 'Pagamento de Condominio no mês', false),
  (3686, 'pagagua', 'Pagamento de Conta de Agua no mês', false),
  (3687, 'pagalug', 'Pagamento de Aluguel no mês', false),
  (3688, 'pagcorr', 'Pagamento de Despesas de Correio no mês', false),
  (3689, 'pagadsal', 'Pagamento de Adiantamento salarial do mês', false),
  (3690, 'apropseg', 'Apropriação de seguros no mês', false),
  (3691, 'Gás', 'Pagamento de Gás ref.', false),
  (3692, 'Internet', 'Pagamento de Internet ref.', false),
  (3693, 'adtosoc', 'Pagamento de Adiantamento a sócios ref.', false),
  (3694, 'devadtosoc', 'Devolução de Adiantamento a sócios ref.', false),
  (3695, 'Taxadmcnt', 'Taxa Administração de Conta ref.', false),
  (3696, 'intecap', 'Capital Social a Integralizar Conf. Contrato Social', false),
  (3697, 'RECEBJUROS', 'Recebimento de juros de clientes cfe NF nº', false),
  (3698, 'iofaplic', 'Pagamento de IOF s/ aplicação financeira ref.', false),
  (3699, NULL, 'Pagamento de Associação de Classe ref.', false),
  (3700, NULL, 'Pagamento de Vale Refeição', false),
  (3701, NULL, 'Pagamento de Vale Alimentação', false),
  (3702, NULL, 'Pagamento de Iptu ref.', false),
  (3703, NULL, 'Pagamento de despesas com cartório ref.', false),
  (3704, NULL, 'Compra de Material de Limpeza ref.', false),
  (3705, NULL, 'Pagamento de serviços ref.', false),
  (3706, NULL, 'Pagamento de adiantamento ref.', false),
  (3707, NULL, 'Pagamento de Assistencia Médica ref.', false),
  (3708, NULL, 'Pagamento em duplicidade ref.', false),
  (3709, NULL, 'Pagamento IOF ref.', false),
  (3710, NULL, 'Pagamento de ISS ref.', false),
  (3711, NULL, 'Pagamento de Empréstimo Parc.', false),
  (3712, NULL, 'Pagamento de Seguro ref.', false),
  (3713, NULL, 'Reembolso de Despesas conf. ND nº', false),
  (3714, NULL, 'Adto. p/Futuro Aumento de Capital ref.', false),
  (3715, NULL, 'Apropriação do Resultado do exercicio:', false),
  (3716, NULL, 'Adiantamento para Futuro Aumento de Capital em:', false),
  (3717, NULL, 'Venda de sucatas de equipamentos e outros', false),
  (3718, NULL, 'Receita de variação cambial', false),
  (3719, 'Pagamento de PCC', 'Pagamento de Pis/Cofins/CSLL ref.:', false),
  (3720, NULL, 'Variação Cambial ref. NF:', false),
  (3721, NULL, 'Recebimento de', false),
  (3722, NULL, 'Desconto Obtido ref.', false),
  (3723, NULL, 'Pagamento de Empréstimo ref.', false),
  (3724, NULL, 'Pagamento de Reembolso de Despesas conf. ND nº', false),
  (3725, NULL, 'Pagamento de Refeição ref.', false),
  (3726, NULL, 'Pagamento de despesas com copa e cozinha ref.', false),
  (3727, NULL, 'Pagamento de licença de uso ref.', false),
  (3728, NULL, 'Pagamento de despesas com viagens e hospedagens ref.', false),
  (3729, NULL, 'Pagamento de Confraternizações ref.', false),
  (3730, NULL, 'Pagamento de Condução ref.', false),
  (3731, NULL, 'Devolução de Adiantamento para Futuro Aumento de Capital em:', false),
  (3732, NULL, 'Pagamento de serviços de Limpeza ref.', false),
  (3733, NULL, 'Pagamento de Estacionamento ref.', false),
  (3734, NULL, 'Compra de Material de Escritório ref.', false),
  (3735, NULL, 'Pagamento de Férias Ref.', false),
  (3736, NULL, 'Pagamento de Refeições Ref.', false),
  (3737, NULL, 'Pagamento de Brindes Ref.', false),
  (3738, NULL, 'Pagamento de Assistencia Odontológica ref.', false),
  (3739, NULL, 'Pagamento de Doação para', false),
  (3740, NULL, 'Recebimento de Reembolso de Despesas ref.', false),
  (3741, NULL, 'Pagamento de Compra de Livros ref.', false),
  (3742, NULL, 'Resultado de Equivalência Patrimonial ref.', false),
  (3743, NULL, 'Pagamento de Imposto indevido ou a maior ref.', false),
  (3744, NULL, 'Pagamento de Reembolso de Despesas ref.', false),
  (3745, NULL, 'Pagamento 1ª parcela 13° salário ref.', false),
  (3746, NULL, 'Pagamento 2ª parcela 13° salário ref.', false),
  (3747, NULL, 'Pagamento de Manutenção, Reparos e Instalações ref.', false),
  (3748, NULL, 'Pagamento de Rescisão ref.', false),
  (3749, NULL, 'Reembolso de Despesas ref.', false),
  (3750, NULL, 'Pagamento de Copias e Autenticações ref.', false),
  (3751, NULL, 'Pagamento de Assinatura ref.', false),
  (3752, NULL, 'Pagamento de Compra de Benefícios ref.', false),
  (3753, NULL, 'Compra de Material de Consumo ref.', false),
  (3754, NULL, 'Pagamento de Patrocínio ref.', false),
  (3755, NULL, 'Compra de Bens de Pequeno Valor ref.', false),
  (3756, NULL, 'Pagamento de Dominio ref.', false),
  (3757, NULL, 'Pagamento de parcelamento de impostos federais ref.', false),
  (3758, NULL, 'Pagamento de parcelamento de impostos municipais ref.', false),
  (3759, NULL, 'Pagamento de IPVA ref.', false),
  (3761, NULL, 'Pagamento de Despesas com Farmácia ref.', false),
  (3760, NULL, 'Pagamento de Aluguel de Equipamentos ref.', false),
  (3763, NULL, 'Pagamento de Plantas e Flores ref.', false),
  (3762, NULL, 'Pagamento de Repasse a Cliente Ref.', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;

INSERT INTO historicos_sci_lcr (codigo, apelido, nome, pula_complemento) VALUES
  (3764, NULL, 'Pagamento de Impressão de Materiais ref.', false),
  (3765, NULL, 'Pagamento de serviços tomados autônomo ref.', false),
  (3766, NULL, 'Pagamento de bens do ativo imobilizado ref.', false),
  (3767, NULL, 'Compras de materiais para copa e cozinha ref.', false),
  (3768, NULL, 'Receita Com Variação Monetária ref.', false),
  (3769, NULL, 'Compensação de Impostos Federais ref.', false),
  (3770, NULL, 'Compensação de Impostos Municipais ref.', false),
  (3771, NULL, 'Restituição de Impostos Federais ref.', false),
  (3772, NULL, 'Restituição de Impostos Municipais ref.', false),
  (3773, NULL, 'Pagamento de Juros Sobre Impostos ref.', false),
  (3774, NULL, 'Pagamento de Multas Sobre Impostos ref.', false),
  (3775, NULL, 'Perdas com Aplicação Financeira no mês', false),
  (3776, NULL, 'Recebimento de Caução ref.', false),
  (3777, NULL, 'Pagamento de Multa de Trânsito ref.', false),
  (3778, NULL, 'Pagamento de Licenciamento de Veículo ref.', false),
  (3779, NULL, 'Aquisição de Seguro ref.', false),
  (3780, NULL, 'Pagamento de Contribuição Sindical ref.', false),
  (3781, NULL, 'Pagamento de Contribuição Assistencial ref.', false),
  (3782, NULL, 'Pagamento de Contribuição Confederativa ref.', false),
  (3783, NULL, 'Pagamento de CIDE ref.', false),
  (3784, NULL, 'Pagamento de Guia Unificada de Impostos ref.', false),
  (3785, NULL, 'Pagamento de Cursos e Treinamentos ref.', false),
  (3786, NULL, 'Pagamento de Assinatura de Jornais, Revistas e Boletins ref.', false),
  (3787, NULL, 'Pagamento de Multa e Juros s/Tributos ref.', false),
  (3788, NULL, 'Correção monetária ref.', false),
  (3789, NULL, 'Pagamento de Participação nos Lucros e Resultados ref.', false),
  (3790, NULL, 'Recebimento de clientes cfe', false),
  (3791, NULL, 'Pagamento de serviços tomados ref.', false),
  (3792, NULL, 'Pagamento de seguro de vida em grupo ref.', false),
  (3793, NULL, 'Pagamento de Despesas com Transporte ref.', false),
  (3794, NULL, 'Recebimento de Juros Ativos no Trimestre', false),
  (3795, NULL, 'Descontos Obtidos no Trimestre', false),
  (3796, NULL, 'Juros s/ Mútuo', false),
  (3797, NULL, 'Outras Receitas', false),
  (3798, NULL, 'Pagamento de Despesas Legais e Judiciais Ref.', false),
  (3799, NULL, 'Compra de Material de Higiene Ref.', false),
  (3800, NULL, 'Pagamento de Anuidade de Cartão de Crédito Ref.', false),
  (3801, NULL, 'Recebimento Parcela n° 1  N° Doc.', false),
  (3802, NULL, 'Pagamento de Despesa com Participação em Feiras e Eventos Ref.', false),
  (3803, NULL, 'Receita Com Ganho de Capital ref.', false),
  (3804, NULL, 'Perdas Na Alienação de Bens do Ativo Imobilizado Ref.', false),
  (3805, NULL, 'Recebimento de Empréstimo Ref.', false),
  (3806, NULL, 'Pagamento de Material de Escritório ref.', false),
  (3807, NULL, 'Pagamento de Consórcio Ref.', false),
  (3808, NULL, 'Pagamento de ITBI Ref.', false),
  (3809, NULL, 'Distribuição de Lucros a Pagar ref.', false),
  (3810, NULL, 'Recibo de distribuição de lucros para', false),
  (3811, 'IRRF RETIDO', 'IRRF retido s/ Retirada de Lucro ref.:', false),
  (3812, NULL, 'Desconto de Benefício ref.:', false),
  (3813, NULL, 'Pagamento de Hospedagens de Sites Ref.', false),
  (3814, NULL, 'Pedido de parcelamento de impostos federais ref.', false),
  (3815, NULL, 'Pedido de parcelamento de impostos municipais ref.', false),
  (3816, NULL, 'Encargos sobre o parcelamento de impostos ref.', false),
  (3817, 'Variação cambial', 'variação cambial passiva ref.', false),
  (3818, NULL, 'Fatura de Conta de Internet nº', false),
  (3819, 'Despesa antecipada', 'Despesa antecipada ref.:', false),
  (3820, NULL, 'Compra de Benefícios conf.', false),
  (3821, NULL, 'Apropriação de Receita ref.', false),
  (3822, NULL, 'Gastos com viagens e hospedagens ref.', false),
  (3823, 'Juros Ativo', 'Recebimento de Juros Ativo Ref.:', false)
  ON CONFLICT (codigo) DO UPDATE SET apelido=EXCLUDED.apelido, nome=EXCLUDED.nome, pula_complemento=EXCLUDED.pula_complemento;
