/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedCxRouteImport } from './routes/_authenticated/cx'
import { Route as AuthenticatedConsultiveRouteImport } from './routes/_authenticated/consultive'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedRevisarDocumentoIdRouteImport } from './routes/_authenticated/revisar.$documentoId'
import { Route as AuthenticatedCxEmpresaIdRouteImport } from './routes/_authenticated/cx_.$empresaId'
import { Route as AuthenticatedConsultiveEmpresaIdRouteImport } from './routes/_authenticated/consultive_.$empresaId'
import { Route as AuthenticatedConciliacaoEmpresaIdRouteImport } from './routes/_authenticated/conciliacao_.$empresaId'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes_.$id'
import { Route as AuthenticatedKnowledgeProcessoCodigoRouteImport } from './routes/_authenticated/knowledge_.processo.$codigo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCxRoute = AuthenticatedCxRouteImport.update({
  id: '/cx',
  path: '/cx',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultiveRoute = AuthenticatedConsultiveRouteImport.update({
  id: '/consultive',
  path: '/consultive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarDocumentoIdRoute =
  AuthenticatedRevisarDocumentoIdRouteImport.update({
    id: '/revisar/$documentoId',
    path: '/revisar/$documentoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCxEmpresaIdRoute =
  AuthenticatedCxEmpresaIdRouteImport.update({
    id: '/cx_/$empresaId',
    path: '/cx/$empresaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultiveEmpresaIdRoute =
  AuthenticatedConsultiveEmpresaIdRouteImport.update({
    id: '/consultive_/$empresaId',
    path: '/consultive/$empresaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoEmpresaIdRoute =
  AuthenticatedConciliacaoEmpresaIdRouteImport.update({
    id: '/conciliacao_/$empresaId',
    path: '/conciliacao/$empresaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeProcessoCodigoRoute =
  AuthenticatedKnowledgeProcessoCodigoRouteImport.update({
    id: '/knowledge_/processo/$codigo',
    path: '/knowledge/processo/$codigo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultive': typeof AuthenticatedConsultiveRoute
  '/cx': typeof AuthenticatedCxRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/conciliacao/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/consultive/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/cx/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/revisar/$documentoId': typeof AuthenticatedRevisarDocumentoIdRoute
  '/knowledge/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultive': typeof AuthenticatedConsultiveRoute
  '/cx': typeof AuthenticatedCxRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/conciliacao/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/consultive/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/cx/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/revisar/$documentoId': typeof AuthenticatedRevisarDocumentoIdRoute
  '/knowledge/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consultive': typeof AuthenticatedConsultiveRoute
  '/_authenticated/cx': typeof AuthenticatedCxRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/clientes_/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/conciliacao_/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/_authenticated/consultive_/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/_authenticated/cx_/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/_authenticated/revisar/$documentoId': typeof AuthenticatedRevisarDocumentoIdRoute
  '/_authenticated/knowledge_/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/consultive'
    | '/cx'
    | '/documentos'
    | '/historico'
    | '/knowledge'
    | '/lancamentos'
    | '/tarefas'
    | '/clientes/$id'
    | '/conciliacao/$empresaId'
    | '/consultive/$empresaId'
    | '/cx/$empresaId'
    | '/revisar/$documentoId'
    | '/knowledge/processo/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/consultive'
    | '/cx'
    | '/documentos'
    | '/historico'
    | '/knowledge'
    | '/lancamentos'
    | '/tarefas'
    | '/clientes/$id'
    | '/conciliacao/$empresaId'
    | '/consultive/$empresaId'
    | '/cx/$empresaId'
    | '/revisar/$documentoId'
    | '/knowledge/processo/$codigo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/clientes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consultive'
    | '/_authenticated/cx'
    | '/_authenticated/documentos'
    | '/_authenticated/historico'
    | '/_authenticated/knowledge'
    | '/_authenticated/lancamentos'
    | '/_authenticated/tarefas'
    | '/_authenticated/clientes_/$id'
    | '/_authenticated/conciliacao_/$empresaId'
    | '/_authenticated/consultive_/$empresaId'
    | '/_authenticated/cx_/$empresaId'
    | '/_authenticated/revisar/$documentoId'
    | '/_authenticated/knowledge_/processo/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cx': {
      id: '/_authenticated/cx'
      path: '/cx'
      fullPath: '/cx'
      preLoaderRoute: typeof AuthenticatedCxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultive': {
      id: '/_authenticated/consultive'
      path: '/consultive'
      fullPath: '/consultive'
      preLoaderRoute: typeof AuthenticatedConsultiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar/$documentoId': {
      id: '/_authenticated/revisar/$documentoId'
      path: '/revisar/$documentoId'
      fullPath: '/revisar/$documentoId'
      preLoaderRoute: typeof AuthenticatedRevisarDocumentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cx_/$empresaId': {
      id: '/_authenticated/cx_/$empresaId'
      path: '/cx/$empresaId'
      fullPath: '/cx/$empresaId'
      preLoaderRoute: typeof AuthenticatedCxEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultive_/$empresaId': {
      id: '/_authenticated/consultive_/$empresaId'
      path: '/consultive/$empresaId'
      fullPath: '/consultive/$empresaId'
      preLoaderRoute: typeof AuthenticatedConsultiveEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao_/$empresaId': {
      id: '/_authenticated/conciliacao_/$empresaId'
      path: '/conciliacao/$empresaId'
      fullPath: '/conciliacao/$empresaId'
      preLoaderRoute: typeof AuthenticatedConciliacaoEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes_/$id': {
      id: '/_authenticated/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge_/processo/$codigo': {
      id: '/_authenticated/knowledge_/processo/$codigo'
      path: '/knowledge/processo/$codigo'
      fullPath: '/knowledge/processo/$codigo'
      preLoaderRoute: typeof AuthenticatedKnowledgeProcessoCodigoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsultiveRoute: typeof AuthenticatedConsultiveRoute
  AuthenticatedCxRoute: typeof AuthenticatedCxRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedConciliacaoEmpresaIdRoute: typeof AuthenticatedConciliacaoEmpresaIdRoute
  AuthenticatedConsultiveEmpresaIdRoute: typeof AuthenticatedConsultiveEmpresaIdRoute
  AuthenticatedCxEmpresaIdRoute: typeof AuthenticatedCxEmpresaIdRoute
  AuthenticatedRevisarDocumentoIdRoute: typeof AuthenticatedRevisarDocumentoIdRoute
  AuthenticatedKnowledgeProcessoCodigoRoute: typeof AuthenticatedKnowledgeProcessoCodigoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsultiveRoute: AuthenticatedConsultiveRoute,
  AuthenticatedCxRoute: AuthenticatedCxRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedConciliacaoEmpresaIdRoute:
    AuthenticatedConciliacaoEmpresaIdRoute,
  AuthenticatedConsultiveEmpresaIdRoute: AuthenticatedConsultiveEmpresaIdRoute,
  AuthenticatedCxEmpresaIdRoute: AuthenticatedCxEmpresaIdRoute,
  AuthenticatedRevisarDocumentoIdRoute: AuthenticatedRevisarDocumentoIdRoute,
  AuthenticatedKnowledgeProcessoCodigoRoute:
    AuthenticatedKnowledgeProcessoCodigoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
