-- LCR · dados reais (plano de contas + colunas de lançamento + lançamentos demo)
-- Corrigido ao schema real. Rodar APÓS 01 (clientes) e 03 (históricos), que já foram aplicados.
BEGIN;

-- 02 · Plano de contas (1187) — corrigido: codigo::text, CHECK de tipo removido, hierarquia achatada
ALTER TABLE public.plano_contas DROP CONSTRAINT IF EXISTS plano_contas_tipo_check;
TRUNCATE TABLE public.plano_contas RESTART IDENTITY CASCADE;
CREATE TEMP TABLE _pc(codigo int, descricao text, tipo text, ativo boolean) ON COMMIT DROP;
INSERT INTO _pc (codigo, descricao, tipo, ativo) VALUES
  (1, 'ATIVO', 'ativo', TRUE),
  (2, 'ATIVO CIRCULANTE', 'ativo', TRUE),
  (3, 'DISPONIBILIDADES', 'ativo', TRUE),
  (4, 'CAIXA', 'ativo', TRUE),
  (5, 'Caixa', 'ativo', TRUE),
  (948, 'Caixa em Poder de Terceiros', 'ativo', TRUE),
  (1086, 'Caixa', 'ativo', TRUE),
  (1091, 'Caixa SCP Osirius', 'ativo', TRUE),
  (1092, 'Caixa SCP R2EAC', 'ativo', TRUE),
  (1093, 'Caixa SCP OPTA', 'ativo', TRUE),
  (1136, 'Caixa em Moeda Estrangeira', 'ativo', TRUE),
  (1161, 'Caixa BSB', 'ativo', TRUE),
  (6, 'BANCOS CONTA MOVIMENTO', 'ativo', TRUE),
  (7, 'Banco do Brasil', 'ativo', TRUE),
  (8, 'Banco Caixa Econômica Federal', 'ativo', TRUE),
  (9, 'Banco Bradesco', 'ativo', TRUE),
  (10, 'Banco Santander', 'ativo', TRUE),
  (657, 'Banco Itaú 1', 'ativo', TRUE),
  (658, 'Banco Inter', 'ativo', TRUE),
  (659, 'Banco Sicoob', 'ativo', TRUE),
  (775, 'Banco Sicredi Vale', 'ativo', TRUE),
  (779, 'Banco Original', 'ativo', TRUE),
  (802, 'Banco Pagar.me', 'ativo', TRUE),
  (808, 'Banco e Financeira Omni', 'ativo', TRUE),
  (809, 'Banco C6', 'ativo', TRUE),
  (815, 'Banco Semear', 'ativo', TRUE),
  (818, 'Banco Safra S/A', 'ativo', TRUE),
  (821, 'Banco Nubank', 'ativo', TRUE),
  (823, 'Banco XP Investimentos', 'ativo', TRUE),
  (830, 'Banco BS2', 'ativo', TRUE),
  (860, 'Banco Paypal', 'ativo', TRUE),
  (840, 'Banco Wirecard', 'ativo', TRUE),
  (866, 'Banco Itaú 2', 'ativo', TRUE),
  (867, 'Banco Itaú 3', 'ativo', TRUE),
  (868, 'Banco Itaú 4', 'ativo', TRUE),
  (888, 'Banco Votorantim', 'ativo', TRUE),
  (910, 'Banco Stone Pagamentos', 'ativo', TRUE),
  (916, 'Banco Rendimento', 'ativo', TRUE),
  (917, 'Banco Cora', 'ativo', TRUE),
  (930, 'Banco Biz', 'ativo', TRUE),
  (935, 'Banco Unicred', 'ativo', TRUE),
  (936, 'Banco Linker', 'ativo', TRUE),
  (946, 'Banco PagBank', 'ativo', TRUE),
  (955, 'Banco PJBank', 'ativo', TRUE),
  (960, 'Mercado Pago', 'ativo', TRUE),
  (975, 'Banco de La Nacion Argentina', 'ativo', TRUE),
  (1021, 'Banco Millennium', 'ativo', TRUE),
  (1024, 'Banco Paymee', 'ativo', TRUE),
  (1031, 'Banco BTG Pactual 1', 'ativo', TRUE),
  (1037, 'Banco Mercantil do Brasil', 'ativo', TRUE),
  (1048, 'Banco do Brasil 1', 'ativo', TRUE),
  (1049, 'BB C/C 56164-9 - Juju Boot Camp', 'ativo', TRUE),
  (1050, 'BB C/C 56165-7 - Juju Boot Camp', 'ativo', TRUE),
  (1109, 'BB C/C 64151-0 - Era Uma Vez', 'ativo', TRUE),
  (1110, 'BB C/C 60879-3 - Rodeio Rock', 'ativo', TRUE),
  (1167, 'BB C/C 66007-8 - Rodeio Rock', 'ativo', TRUE),
  (1311, 'BB C/C 71584-0 – Só Nós Dois', 'ativo', TRUE),
  (1312, 'BB C/C 71585-9 – Só Nós Dois', 'ativo', TRUE),
  (1081, 'Banco XP Investimentos II', 'ativo', TRUE),
  (1102, 'Banco Omie Cash', 'ativo', TRUE),
  (1113, 'Receba Fácil', 'ativo', TRUE),
  (1114, 'Banco BTG Pactual 2', 'ativo', TRUE),
  (1117, 'Banco do Brasil 2', 'ativo', TRUE),
  (1133, 'Travelex Bank', 'ativo', TRUE),
  (1137, 'Banco Contabilizei.bank', 'ativo', TRUE),
  (1157, 'Travelex Bank - CAD', 'ativo', TRUE),
  (1158, 'Travelex Bank - USD', 'ativo', TRUE),
  (1159, 'Travelex Bank - GBP', 'ativo', TRUE),
  (1160, 'Travelex Bank - EUR', 'ativo', TRUE),
  (1169, 'Omie - Extrato Justa', 'ativo', TRUE),
  (1180, 'Socinal S.A - Crédito', 'ativo', TRUE),
  (1196, 'Banco Caixa Econômica Federal 2', 'ativo', TRUE),
  (1197, 'Banco Afinz', 'ativo', TRUE),
  (1207, 'Banco Bradesco 2', 'ativo', TRUE),
  (1208, 'Banco Sisprime', 'ativo', TRUE),
  (1211, 'Banco Sisprime', 'ativo', TRUE),
  (1213, 'Banco Iugu', 'ativo', TRUE),
  (1214, 'Banco Ourinvest', 'ativo', TRUE),
  (1215, 'Banco Ourinvest', 'ativo', TRUE),
  (1258, 'Banco Kamino', 'ativo', TRUE),
  (1259, 'Banco Kamino', 'ativo', TRUE),
  (1276, 'Banco Asas', 'ativo', TRUE),
  (1277, 'Banco Asas', 'ativo', TRUE),
  (1284, 'Banco C6 Conta Global', 'ativo', TRUE),
  (1287, 'Banco Santander 2', 'ativo', TRUE),
  (1292, 'Banco Wise', 'ativo', TRUE),
  (1293, 'Banco Wise - Global', 'ativo', TRUE),
  (1294, 'Banco LCR Bank', 'ativo', TRUE),
  (1295, 'Banco LCR Bank', 'ativo', TRUE),
  (1323, 'Banco Celcoin S.A.', 'ativo', TRUE),
  (1324, 'Banco Celcoin S.A.', 'ativo', TRUE),
  (1327, 'Banco Infinitepay', 'ativo', TRUE),
  (1328, 'Conta Global - EURO', 'ativo', TRUE),
  (1329, 'Conta Global - Dolar', 'ativo', TRUE),
  (1333, 'Banco Banestes', 'ativo', TRUE),
  (1334, 'Banco Banestes', 'ativo', TRUE),
  (1336, 'Banco Wise', 'ativo', TRUE),
  (1337, 'Banco Wise - Euro', 'ativo', TRUE),
  (1338, 'Banco Wise - Dolar', 'ativo', TRUE),
  (1343, 'Banco Sicoob 2', 'ativo', TRUE),
  (1346, 'Moneycorp Banco de Cambio S.A.', 'ativo', TRUE),
  (1364, 'Banco C6 Conta Global Dólar', 'ativo', TRUE),
  (11, 'APLICAÇÕES DE LIQUIDEZ IMEDIATA', 'ativo', TRUE),
  (12, 'Aplicação - Banco do Brasil', 'ativo', TRUE),
  (13, 'Aplicação - Caixa Econômica Federal', 'ativo', TRUE),
  (660, 'Aplicação - Banco Bradesco', 'ativo', TRUE),
  (661, 'Aplicação - Banco Itaú 1', 'ativo', TRUE),
  (662, 'Aplicação - Banco Santander', 'ativo', TRUE),
  (663, 'Aplicação - Banco Inter', 'ativo', TRUE),
  (664, 'Aplicação - Banco Sicoob', 'ativo', TRUE),
  (708, 'Aplicação - Banco Paraná', 'ativo', TRUE),
  (713, 'Aplicação - Banco Sofisa', 'ativo', TRUE),
  (714, 'Aplicação - Banco Daycoval', 'ativo', TRUE),
  (811, 'Aplicação - Banco C6', 'ativo', TRUE),
  (810, 'Aplicação - Banco Original', 'ativo', TRUE),
  (816, 'Aplicação - Banco Semear', 'ativo', TRUE),
  (819, 'Aplicação - Banco Safra S/A', 'ativo', TRUE),
  (822, 'Aplicação - Banco Nubank', 'ativo', TRUE),
  (824, 'Aplicação - Banco XP Investimentos', 'ativo', TRUE),
  (825, 'Aplicação - Guide Investimentos', 'ativo', TRUE),
  (831, 'Aplicação - Banco BS2', 'ativo', TRUE),
  (873, 'Aplicação - Banco Itaú 2', 'ativo', TRUE),
  (874, 'Aplicação - Banco Itaú 3', 'ativo', TRUE),
  (875, 'Aplicação - Banco Itaú 4', 'ativo', TRUE),
  (918, 'Aplicação - Banco Rendimento', 'ativo', TRUE),
  (938, 'Aplicação - Banco Unicred', 'ativo', TRUE),
  (953, 'Aplicação - Banco Inter 2', 'ativo', TRUE),
  (961, 'Aplicação - Mercado Pago', 'ativo', TRUE),
  (979, 'Aplicação - Fundo ITAÚ RF Simples', 'ativo', TRUE),
  (980, 'Aplicação - Seleção ABS HEDGE', 'ativo', TRUE),
  (981, 'Aplicação - Multifundos MM', 'ativo', TRUE),
  (1036, 'Aplicação - Banco Itaú 5', 'ativo', TRUE),
  (1077, 'Aplicação - Banco Bradesco 2', 'ativo', TRUE),
  (1082, 'Aplicação - Banco XP Investimentos II', 'ativo', TRUE),
  (1103, 'Aplicação - Banco BTG', 'ativo', TRUE),
  (1115, 'Aplicação - Banco BTG 2', 'ativo', TRUE),
  (1118, 'Aplicação - Banco do Brasil 2', 'ativo', TRUE),
  (1119, 'Aplicação - Banco Inter 3', 'ativo', TRUE),
  (1162, 'Aplicação - Banco Votorantim', 'ativo', TRUE),
  (1166, 'Aplicação - Banco Sicredi Vale', 'ativo', TRUE),
  (1168, 'Aplicação - Banco do Brasil 66007-8 – Rodeio Rock', 'ativo', TRUE),
  (1170, 'Aplicação - Banco XP Investimentos', 'ativo', TRUE),
  (1172, 'Aplicação XP Investimentos Renda Fixa', 'ativo', TRUE),
  (1173, 'Aplicação XP Investimentos Fundo de investimento', 'ativo', TRUE),
  (1174, 'Aplicação XP Investimentos Fundo imobiliário', 'ativo', TRUE),
  (1200, 'Aplicação - Banco Safra', 'ativo', TRUE),
  (1201, 'Aplicação - Banco Safra Vtr Vitesse', 'ativo', TRUE),
  (1202, 'Aplicação - Banco Safra Dir Saf Di Mast', 'ativo', TRUE),
  (1203, 'Aplicação - Banco Safra Eol Saf Galileo Spe', 'ativo', TRUE),
  (1204, 'Aplicação - Banco Safra Saf Soberano Inst Fc Rf Simpls', 'ativo', TRUE),
  (1205, 'Aplicação - Banco Safra Renda Fixa', 'ativo', TRUE),
  (1206, 'Aplicação - Banco Safra Agilite Cp', 'ativo', TRUE),
  (1209, 'Aplicação - Sisprime', 'ativo', TRUE),
  (1210, 'Aplicação - Sisprime', 'ativo', TRUE),
  (1313, 'Aplicação - Banco do Brasil 71584-0 – Só Nós Dois', 'ativo', TRUE),
  (1314, 'Aplicação - Banco do Brasil 71585-9 – Só Nós Dois', 'ativo', TRUE),
  (14, 'DIREITOS REALIZÁVEIS A CURTO PRAZO', 'ativo', TRUE),
  (15, 'CLIENTES NACIONAIS', 'ativo', TRUE),
  (16, 'Clientes nacionais', 'ativo', TRUE),
  (17, 'CLIENTES NACIONAIS', 'ativo', TRUE),
  (18, 'Clientes Diversos', 'ativo', TRUE),
  (1176, 'CCB A3342680 Diones Krause', 'ativo', TRUE),
  (1177, 'CCB A3276281 Marcelo Santos', 'ativo', TRUE),
  (1178, 'CCB A3413791 Leonardo Soares Direne', 'ativo', TRUE),
  (1179, 'CCB A3337476 Wagner Correa Longo', 'ativo', TRUE),
  (1182, 'CCB A3437052 Larissa Soares', 'ativo', TRUE),
  (19, 'CLIENTES INTERNACIONAIS', 'ativo', TRUE),
  (34, 'Clientes Internacionais', 'ativo', TRUE),
  (21, 'CARTÕES DE CRÉDITO', 'ativo', TRUE),
  (22, 'Cartão Mastercard', 'ativo', TRUE),
  (23, 'Cartão Redeshop', 'ativo', TRUE),
  (674, 'Cartão Visa', 'ativo', TRUE),
  (778, 'Cartão de Débito/Crédito', 'ativo', TRUE),
  (847, 'Cartão - Paypal', 'ativo', TRUE),
  (848, 'Cartão - Wirecard', 'ativo', TRUE),
  (1002, 'Cartão - Pagar.me', 'ativo', TRUE),
  (1094, 'Cartão - ELO', 'ativo', TRUE),
  (24, 'APLICAÇÕES FINANCEIRAS DE RENDA FIXA', 'ativo', TRUE),
  (25, 'Aplicações no fundo de commodities', 'ativo', TRUE),
  (26, 'Aplicações no fundo DI', 'ativo', TRUE),
  (845, 'Aplicações MASTER DI', 'ativo', TRUE),
  (846, 'Aplicações CDB', 'ativo', TRUE),
  (861, 'Aplicações MASTER FICFI', 'ativo', TRUE),
  (862, 'Aplicações IBIUNA HEDGE MM FICFI', 'ativo', TRUE),
  (863, 'Aplicações INDEX US TECH', 'ativo', TRUE),
  (869, 'Aplicações Itaú 1', 'ativo', TRUE),
  (870, 'Aplicações Itaú 2', 'ativo', TRUE),
  (871, 'Aplicações Itaú 3', 'ativo', TRUE),
  (872, 'Aplicações Itaú 4', 'ativo', TRUE),
  (885, 'Aplicações DI TOP', 'ativo', TRUE),
  (886, 'Aplicações FIC TIT PUB RF REF DI', 'ativo', TRUE),
  (890, 'Aplicações COE', 'ativo', TRUE),
  (924, 'Aplicações Itaú 5', 'ativo', TRUE),
  (959, 'Aplicações Bradesco - FICFI RF DI Safira', 'ativo', TRUE),
  (972, 'Aplicações PRIVILEGE RF REF DI FICFI', 'ativo', TRUE),
  (978, 'Fundo ITAÚ RF Simples', 'ativo', TRUE),
  (982, 'Aplicação Facta Financeira SA CFI', 'ativo', TRUE),
  (983, 'Aplicação Banco Luso Brasileiro S/A', 'ativo', TRUE),
  (984, 'Aplicação Portocred SA Credito Financiamento e Inv', 'ativo', TRUE),
  (985, 'Aplicação Avista S/A - Credito, Financiamento e In', 'ativo', TRUE),
  (986, 'Aplicação Santinvest SA CFI', 'ativo', TRUE),
  (987, 'Aplicação Estrela Mineira Credito Financiamento In', 'ativo', TRUE),
  (988, 'Aplicação Banco Semear S/A', 'ativo', TRUE),
  (989, 'Aplicação Banco Arbi S/A', 'ativo', TRUE),
  (990, 'Aplicação FIDC Anga Multiestrategia I', 'ativo', TRUE),
  (991, 'Aplicação Banco Paulista SA', 'ativo', TRUE),
  (992, 'Aplicação Banco Modal SA', 'ativo', TRUE),
  (993, 'Aplicação Biorc CFI', 'ativo', TRUE),
  (994, 'Ativa Investimentos', 'ativo', TRUE),
  (995, 'Galápagos WM', 'ativo', TRUE),
  (996, 'Aplicação Socopa Corretora', 'ativo', TRUE),
  (1032, 'Aplicação Financeira - Banco Pan', 'ativo', TRUE),
  (1033, 'Aplicação Financeira - Ágora', 'ativo', TRUE),
  (1052, 'Aplicação RF Banco do Brasil', 'ativo', TRUE),
  (1053, 'Aplicação RF BB C/C 56164-9 - Juju', 'ativo', TRUE),
  (1054, 'Aplicação RF BB C/C 56165-7 - Juju', 'ativo', TRUE),
  (1111, 'Aplicação RF BB C/C 64151-0 - Era Uma Vez', 'ativo', TRUE),
  (1112, 'Aplicação BB C/C 60879-3 - Rodeio Rock', 'ativo', TRUE),
  (1078, 'Aplicação FIC Estratégico Multimercado', 'ativo', TRUE),
  (1079, 'Aplicação FIC Maxi Renda Fixa Cred Priv', 'ativo', TRUE),
  (1104, 'Aplicação Banco BTG Pactual', 'ativo', TRUE),
  (1116, 'Aplicação Banco BTG Pactual 2', 'ativo', TRUE),
  (1126, 'Aplicação Caixa Econômica Federal', 'ativo', TRUE),
  (1127, 'Aplicação Caixa Econômica Federal 2', 'ativo', TRUE),
  (1163, 'Aplicação Banco Votorantim', 'ativo', TRUE),
  (1188, 'Aplicação Banco Sicoob', 'ativo', TRUE),
  (1232, 'Aplicação Banco Inter - RF', 'ativo', TRUE),
  (1233, 'Aplicação Banco Inter - Itaú Optimus RF LP Dist Fic Fi', 'ativo', TRUE),
  (1234, 'Aplicação Banco Inter - Inter Inst Financeiras Firf CP', 'ativo', TRUE),
  (1235, 'Aplicação Banco Inter - BTG Pactual Hedge RF', 'ativo', TRUE),
  (1236, 'Aplicação Banco Inter - Inter Liquidez Fic Firf CP RL', 'ativo', TRUE),
  (1237, 'Aplicação Banco Inter - Inter RF Ativa FIRF', 'ativo', TRUE),
  (1308, 'Aplicação CDB banco de La Nacion Argentina', 'ativo', TRUE),
  (1359, 'Aplicação Banco Inter - CRA', 'ativo', TRUE),
  (27, 'APLICAÇÕES FINANCEIRAS DE RENDA VARIÁVEL', 'ativo', TRUE),
  (28, 'Aplicações em ações', 'ativo', TRUE),
  (30, 'Aplicações em caderneta de poupança', 'ativo', TRUE),
  (31, 'Aplicações depósito especial remunerado', 'ativo', TRUE),
  (837, 'Aplicações em Poupança - Bradesco', 'ativo', TRUE),
  (939, 'Capital - Unicred', 'ativo', TRUE),
  (1034, 'Aplicações Criptomoedas', 'ativo', TRUE),
  (1035, 'Criptomoedas', 'ativo', TRUE),
  (29, 'ADIANTAMENTO A SÓCIOS', 'ativo', TRUE),
  (20, 'Adiantamento a Sócios', 'ativo', TRUE),
  (32, 'ADIANTAMENTOS DIVERSOS', 'ativo', TRUE),
  (33, 'Adiantamentos de salários e empregados', 'ativo', TRUE),
  (35, 'Adiantamentos de despesas', 'ativo', TRUE),
  (36, 'Debitos a Regularizar', 'ativo', TRUE),
  (37, 'Adiantamento a fornecedores', 'ativo', TRUE),
  (38, 'Adiantamento 13º Salário', 'ativo', TRUE),
  (39, 'Adiantamento Férias', 'ativo', TRUE),
  (780, 'Adiantamento a terceiros', 'ativo', TRUE),
  (893, 'Caução - Aluguel', 'ativo', TRUE),
  (931, 'Numerários em Trânsito', 'ativo', TRUE),
  (1085, 'Adiantamento de Parcelamento - SRF', 'ativo', TRUE),
  (1095, 'Adiantamentos de viagens', 'ativo', TRUE),
  (1097, 'Alvará Judicial - Repasse', 'ativo', TRUE),
  (40, 'TRIBUTOS E CONTRIBUIÇÕES A COMPENSAR', 'ativo', TRUE),
  (41, 'ICMS a Recuperar', 'ativo', TRUE),
  (42, 'Impostos Pagamentos Indevidos ou a Maior a Recuperar', 'ativo', TRUE),
  (43, 'IRRF a Retido na Fonte a Recuperar', 'ativo', TRUE),
  (44, 'IRPJ Estimado a Recuperar', 'ativo', TRUE),
  (45, 'Contribuição Social Estimada a Recuperar', 'ativo', TRUE),
  (46, 'PIS a Recuperar', 'ativo', TRUE),
  (47, 'COFINS a Recuperar', 'ativo', TRUE),
  (48, 'CSLL a Recuperar', 'ativo', TRUE),
  (49, 'ISS a Recuperar', 'ativo', TRUE),
  (50, 'IRRF a Recuperar', 'ativo', TRUE),
  (51, 'INSS a Recuperar', 'ativo', TRUE),
  (628, 'Pis Não Cumulativo a Recuperar', 'ativo', TRUE),
  (629, 'Cofins Não Cumulativo a Recuperar', 'ativo', TRUE),
  (693, 'IR Retido na Fonte Sobre Aplicações', 'ativo', TRUE),
  (865, 'FGTS a Recuperar', 'ativo', TRUE),
  (925, 'IRPJ a Recuperar - LR', 'ativo', TRUE),
  (926, 'CSLL a Recuperar - LR', 'ativo', TRUE),
  (929, 'Simples a Recuperar', 'ativo', TRUE),
  (1150, 'Saldo negativo IRPJ', 'ativo', TRUE),
  (1151, 'Saldo negativo CSLL', 'ativo', TRUE),
  (52, 'EMPRÉSTIMOS', 'ativo', TRUE),
  (53, 'Mutuo Com Terceiros', 'ativo', TRUE),
  (692, 'Emprestimos a Funcionários', 'ativo', TRUE),
  (54, 'ESTOQUES', 'ativo', TRUE),
  (55, 'Estoque de Mercadoria Para Revenda', 'ativo', TRUE),
  (56, 'Estoque de Matéria-Prima', 'ativo', TRUE),
  (57, 'Estoque de Material de Consumo de Almoxarifado', 'ativo', TRUE),
  (58, 'Estoque de Produtos Em Elaboração', 'ativo', TRUE),
  (59, 'Estoque de Produtos Acabados', 'ativo', TRUE),
  (911, 'Imóveis', 'ativo', TRUE),
  (947, 'Estoque de imobilizado mantido para Venda', 'ativo', TRUE),
  (1218, 'ESTOQUES DE IMOVEIS', 'ativo', TRUE),
  (1220, 'ESTOQUES DE IMOVEIS', 'ativo', TRUE),
  (60, 'DEDUÇÕES DOS DIREITOS', 'ativo', TRUE),
  (61, 'Duplicatas descontadas', 'ativo', TRUE),
  (62, 'Provisão P/ Créditos de Liquidação Duvidosa', 'ativo', TRUE),
  (63, 'Provisão P/Ajuste Aplicação Em Ouro', 'ativo', TRUE),
  (64, 'REMESSA DE PRODUTOS/MERCADORIAS', 'ativo', TRUE),
  (65, 'Remessa de Produtos/Mercadorias', 'ativo', TRUE),
  (66, 'RETORNO DE PRODUTOS/MERCADORIAS', 'ativo', TRUE),
  (67, 'Retorno de Produtos/Mercadorias', 'ativo', TRUE),
  (80, 'TÍTULOS A RECEBER DE TERCEIROS', 'ativo', TRUE),
  (81, 'Despesas Reembolsáveis Receber', 'ativo', TRUE),
  (849, 'Despesas Reembolsáveis Receber - Juju', 'ativo', TRUE),
  (850, 'Despesas Reembolsáveis Receber - Fashion', 'ativo', TRUE),
  (851, 'Despesas Reembolsáveis Receber - Kardec', 'ativo', TRUE),
  (949, 'Despesas de Clientes a Reembolsar', 'ativo', TRUE),
  (1064, 'Despesas Reembolsáveis Receber - Guerreiros', 'ativo', TRUE),
  (1164, 'Despesas Reembolsaveis a Receber - Rodeio Rock', 'ativo', TRUE),
  (68, 'DESPESAS DO EXERCÍCIO SEGUINTE', 'ativo', TRUE),
  (69, 'SEGUROS A APROPRIAR', 'ativo', TRUE),
  (70, 'Seguros a Apropriar', 'ativo', TRUE),
  (71, 'Seguros Contra Roubo a Apropriar', 'ativo', TRUE),
  (72, 'Seguros Contra Lucros Cessantes', 'ativo', TRUE),
  (73, 'ASSINATURAS DE PERIÓDICOS A APROPRIAR', 'ativo', TRUE),
  (74, 'Assinatura de Boletins Jornais Revistas', 'ativo', TRUE),
  (75, 'ALUGUEL ANTECIPADO A APROPRIAR', 'ativo', TRUE),
  (76, 'Aluguel de Bens Imóveis', 'ativo', TRUE),
  (77, 'Aluguel de Bens Móveis', 'ativo', TRUE),
  (944, 'JUROS A APROPRIAR', 'ativo', TRUE),
  (945, 'Juros sobre Financiamento a Apropriar', 'ativo', TRUE),
  (965, 'SERVIÇOS A APROPRIAR', 'ativo', TRUE),
  (966, 'Serviços a Apropriar', 'ativo', TRUE),
  (1282, 'OUTRAS DESPESAS A APROPRIAR', 'ativo', TRUE),
  (1283, 'IPTU a Apropriar', 'ativo', TRUE),
  (1286, 'IPVA a Apropriar', 'ativo', TRUE),
  (1325, 'Despesas a Apropriar', 'ativo', TRUE),
  (1265, 'INVESTIMENTOS', 'ativo', TRUE),
  (1266, 'INVESTIMENTOS', 'ativo', TRUE),
  (1267, 'Investimentos', 'ativo', TRUE),
  (1278, 'OUTRAS CONTAS A RECEBER', 'ativo', TRUE),
  (1279, 'OUTRAS CONTAS A RECEBER', 'ativo', TRUE),
  (1280, 'Outras Contas a Receber', 'ativo', TRUE),
  (78, 'ATIVO NÃO CIRCULANTE', 'ativo', TRUE),
  (79, 'ATIVO REALIZÁVEL A LONGO PRAZO', 'ativo', TRUE),
  (1015, 'APLICAÇÕES FINANCEIRAS DE RENDA FIXA', 'ativo', TRUE),
  (1016, 'Aplicação - Banco XP Investimentos', 'ativo', TRUE),
  (1019, 'Previdência Privada', 'ativo', TRUE),
  (1245, 'Aplicação - Sisprime', 'ativo', TRUE),
  (1246, 'Aplicação - Sisprime', 'ativo', TRUE),
  (82, 'DEPÓSITOS JUDICIAIS', 'ativo', TRUE),
  (83, 'Causas Trabalhistas', 'ativo', TRUE),
  (84, 'PIS sobre receitas operacionais', 'ativo', TRUE),
  (928, 'Depositos Judiciais', 'ativo', TRUE),
  (1017, 'APLICAÇÕES FINANCEIRAS DE RENDA VARIÁVEL', 'ativo', TRUE),
  (1018, 'Aplicações em ações', 'ativo', TRUE),
  (89, 'EMPRÉSTIMOS COM PARTES RELACIONADAS', 'ativo', TRUE),
  (90, 'Empresa A S/A', 'ativo', TRUE),
  (968, 'Adiantamento a sócios', 'ativo', TRUE),
  (769, 'MÚTUOS COM SÓCIOS', 'ativo', TRUE),
  (770, 'Mútuos com Sócios', 'ativo', TRUE),
  (91, 'TITULOS DE CAPITALIZAÇÃO', 'ativo', TRUE),
  (92, 'Ourocap - BB', 'ativo', TRUE),
  (820, 'Uniclass - Itaú', 'ativo', TRUE),
  (844, 'Titulos de Capitalização', 'ativo', TRUE),
  (1007, 'TITULOS A RECEBER', 'ativo', TRUE),
  (1008, 'Cliente - Renegociação do Contas a Receber', 'ativo', TRUE),
  (1191, 'Títulos a receber', 'ativo', TRUE),
  (1330, 'Glosas a Recuperar', 'ativo', TRUE),
  (1009, 'IMPOSTOS A RECUPERAR - PROCESSOS', 'ativo', TRUE),
  (1010, 'Pis a Recuperar Proc. 19679.018557/2003', 'ativo', TRUE),
  (1067, 'MÚTUOS COM TERCEIROS', 'ativo', TRUE),
  (1068, 'Mútuos com Terceiros', 'ativo', TRUE),
  (1250, 'OUTROS CRÉDITOS', 'ativo', TRUE),
  (1251, 'CONTA CORRENTE ENTRE COLIGADAS', 'ativo', TRUE),
  (1252, 'Conta Corrente Entre Coligadas', 'ativo', TRUE),
  (93, 'INVESTIMENTOS', 'ativo', TRUE),
  (94, 'INVESTIMENTOS EM COLIGADAS E CONTROLADAS', 'ativo', TRUE),
  (95, 'Investimento em Coligadas e Controladas', 'ativo', TRUE),
  (921, 'PROPRIEDADES PARA INVESTIMENTO', 'ativo', TRUE),
  (923, 'Imóveis', 'ativo', TRUE),
  (1140, 'Predio Rua Correia Dias, nº58', 'ativo', TRUE),
  (1141, 'Predio Rua Correia Dias, nº40', 'ativo', TRUE),
  (1142, 'Predio Rua Estela, nº156', 'ativo', TRUE),
  (1143, 'Predio Rua Cubatão, nº587', 'ativo', TRUE),
  (1144, 'Predio Rua Cubatão, nº587', 'ativo', TRUE),
  (1145, 'Predio Rua Cubatão, nº587', 'ativo', TRUE),
  (1146, 'Predio Rua Vergueiro, nº3.135', 'ativo', TRUE),
  (1147, 'Predio Rua Vergueiro, nº3.135', 'ativo', TRUE),
  (1148, 'Predio Rua Vergueiro, nº3.135', 'ativo', TRUE),
  (1149, 'Predio Rua Vergueiro, nº3.135', 'ativo', TRUE),
  (1153, 'Predio Rua Correia Dias, nº48', 'ativo', TRUE),
  (1216, 'INVESTIMENTO EM QUOTAS', 'ativo', TRUE),
  (1217, 'Investimento em quotas', 'ativo', TRUE),
  (1296, 'Debêntures', 'ativo', TRUE),
  (1297, 'Debêntures', 'ativo', TRUE),
  (1362, 'DIVIDENDOS A RECEBER', 'ativo', TRUE),
  (1363, 'Dividendos a Receber', 'ativo', TRUE),
  (96, 'IMOBILIZADO', 'ativo', TRUE),
  (97, 'BENS E DIREITOS EM USO', 'ativo', TRUE),
  (98, 'Máquinas e Equipamentos', 'ativo', TRUE),
  (99, 'Móveis e Utensílios', 'ativo', TRUE),
  (100, 'Equipamentos de Comunicação', 'ativo', TRUE),
  (101, 'Imóveis', 'ativo', TRUE),
  (102, 'Veículos', 'ativo', TRUE),
  (103, 'Computadores e periféricos', 'ativo', TRUE),
  (104, 'Direito de uso de linha telefônica', 'ativo', TRUE),
  (105, 'Softwares', 'ativo', TRUE),
  (106, 'Marcas e patentes de invenção', 'ativo', TRUE),
  (107, 'Benfeitorias em imóveis de terceiros', 'ativo', TRUE),
  (108, 'Instalações', 'ativo', TRUE),
  (109, 'Terrenos', 'ativo', TRUE),
  (110, 'Transitoria Entrada de Imobilizado', 'ativo', TRUE),
  (803, 'Obras de arte', 'ativo', TRUE),
  (1005, 'Biblioteca', 'ativo', TRUE),
  (1131, 'Benfeitorias em imóveis próprios', 'ativo', TRUE),
  (1190, 'Ajuste de avaliação patrimonial Imóveis', 'ativo', TRUE),
  (1238, 'Fazendas', 'ativo', TRUE),
  (1239, 'Fazenda Ponte Preta', 'ativo', TRUE),
  (1335, 'Aeronaves', 'ativo', TRUE),
  (1344, 'Embarcações', 'ativo', TRUE),
  (111, 'BENS EM CONSTRUÇÃO', 'ativo', TRUE),
  (112, 'Bens em construção', 'ativo', TRUE),
  (715, 'SOFTWARE EM DESENVOLVIMENTO', 'ativo', TRUE),
  (716, 'Viagens e Hospedagens', 'ativo', TRUE),
  (717, 'Refeiçoes', 'ativo', TRUE),
  (718, 'Serviços Prestado por Terceiros - PJ', 'ativo', TRUE),
  (719, 'Estacionamento', 'ativo', TRUE),
  (720, 'Copa e Cozinha', 'ativo', TRUE),
  (721, 'Combustivel', 'ativo', TRUE),
  (722, 'Condução e Taxi', 'ativo', TRUE),
  (723, 'Alugueis', 'ativo', TRUE),
  (724, 'Internet', 'ativo', TRUE),
  (725, 'Reembolso de Despesas', 'ativo', TRUE),
  (726, 'Energia Eletrica', 'ativo', TRUE),
  (727, 'Livros, Jornais e Revistas', 'ativo', TRUE),
  (728, 'Brindes', 'ativo', TRUE),
  (729, 'Serviços de Informática', 'ativo', TRUE),
  (730, 'Pedagio', 'ativo', TRUE),
  (731, 'Serviços Gráficos', 'ativo', TRUE),
  (732, 'Material de Escritório', 'ativo', TRUE),
  (733, 'Propaganda e Publicidade', 'ativo', TRUE),
  (734, 'Cursos e Treinamentos', 'ativo', TRUE),
  (735, 'Serviços de Terceiros Prestados PF', 'ativo', TRUE),
  (736, 'Quilometragem', 'ativo', TRUE),
  (737, 'Pro - Labore', 'ativo', TRUE),
  (738, 'Salários e ordenados', 'ativo', TRUE),
  (739, 'Telefone', 'ativo', TRUE),
  (740, 'Fretes e entregas', 'ativo', TRUE),
  (741, 'Adiantamento a Fornecedor', 'ativo', TRUE),
  (742, 'Serviços de Advocacia', 'ativo', TRUE),
  (743, 'Recrutamento e Seleção', 'ativo', TRUE),
  (967, 'Software em desenvolvimento', 'ativo', TRUE),
  (113, 'PARTICIPAÇÃO EM CONSÓRCIOS', 'ativo', TRUE),
  (114, 'Consórcio', 'ativo', TRUE),
  (115, '(-) DEPRECIAÇÃO ACUMULADA', 'ativo', TRUE),
  (116, '(-) Máquinas e equipamentos', 'ativo', TRUE),
  (117, '(-) Móveis e Utensílios', 'ativo', TRUE),
  (118, '(-) Equipamentos de Comunicação', 'ativo', TRUE),
  (119, '(-) Imóveis', 'ativo', TRUE),
  (120, '(-) Veículos', 'ativo', TRUE),
  (121, '(-) Computadores Periféricos', 'ativo', TRUE),
  (122, '(-) Luminosos/Placas', 'ativo', TRUE),
  (694, '(-) Instalações', 'ativo', TRUE),
  (1006, '(-) Biblioteca', 'ativo', TRUE),
  (1029, '(-) Bens em construção', 'ativo', TRUE),
  (1345, '(-) Embarcações', 'ativo', TRUE),
  (123, 'ATIVO INTANGÍVEL', 'ativo', TRUE),
  (124, 'BENS DE NATUREZA INTANGÍVEL', 'ativo', TRUE),
  (125, 'Capital Intelectual', 'ativo', TRUE),
  (126, 'Marcas e Patentes de Invenção', 'ativo', TRUE),
  (127, 'Fundo de Comércio', 'ativo', TRUE),
  (128, 'Cessão de Direito de Uso de Software', 'ativo', TRUE),
  (129, 'Direitos Autorais', 'ativo', TRUE),
  (130, 'Softwares ou Programas de Computador', 'ativo', TRUE),
  (131, 'Franquias', 'ativo', TRUE),
  (1080, 'Direitos de Exploração Comercial', 'ativo', TRUE),
  (1339, 'Opção de Compra de Ações (Contrato)', 'ativo', TRUE),
  (132, '(-) AMORTIZAÇÃO ACUMULADA', 'ativo', TRUE),
  (133, '(-) Capital Intelectual', 'ativo', TRUE),
  (134, '(-) Marcas Pat. de Invenção', 'ativo', TRUE),
  (135, '(-) Fundo de Comércio', 'ativo', TRUE),
  (136, '(-) Cessão de Direito de Uso de Software', 'ativo', TRUE),
  (137, '(-) Direitos Autorais', 'ativo', TRUE),
  (138, '(-) Softwares', 'ativo', TRUE),
  (139, '(-) Franquias', 'ativo', TRUE),
  (744, '(-) Benfeitorias em imóveis de terceiros', 'ativo', TRUE),
  (1224, 'OUTROS INVESTIMENTOS', 'ativo', TRUE),
  (1225, 'OUTROS INVESTIMENTOS', 'ativo', TRUE),
  (1227, 'Outros Investimentos', 'ativo', TRUE),
  (140, 'CONTAS DE COMPENSAÇÃO', 'ativo', TRUE),
  (141, 'CONTAS DE COMPENSAÇÃO', 'ativo', TRUE),
  (142, 'CONTAS DE COMPENSAÇÃO', 'ativo', TRUE),
  (143, 'Contas de Compensação', 'ativo', TRUE),
  (144, 'PASSIVO', 'passivo', TRUE),
  (145, 'PASSIVO CIRCULANTE', 'passivo', TRUE),
  (146, 'FORNECEDORES', 'passivo', TRUE),
  (147, 'FORNECEDORES', 'passivo', TRUE),
  (148, 'Fornecedores', 'passivo', TRUE),
  (149, 'FORNECEDORES', 'passivo', TRUE),
  (150, 'Fornecedores Diversos', 'passivo', TRUE),
  (768, 'Fornecedores de Imobilizado', 'passivo', TRUE),
  (1181, 'Fornecedor - Socinal S.A - Crédito', 'passivo', TRUE),
  (151, 'EMPRÉSTIMOS E FINANCIAMENTOS', 'passivo', TRUE),
  (152, 'EMPRÉSTIMOS E FINANCIAMENTOS BANCÁRIOS', 'passivo', TRUE),
  (153, 'Empréstimo Banco do Brasil S/A', 'passivo', TRUE),
  (154, 'Empréstimo Caixa Econômica Federal', 'passivo', TRUE),
  (155, 'Empréstimo BNDES', 'passivo', TRUE),
  (804, 'Empréstimo RCI Brasil', 'passivo', TRUE),
  (805, '(-) Encargos sobre empréstimos a apropriar', 'passivo', TRUE),
  (812, 'Empréstimo Banco Bradesco', 'passivo', TRUE),
  (826, 'Empréstimo Banco Santander', 'passivo', TRUE),
  (827, 'Empréstimo Banco Safra', 'passivo', TRUE),
  (828, 'Empréstimo Banco Itaú', 'passivo', TRUE),
  (878, 'Empréstimo Capital de Giro', 'passivo', TRUE),
  (895, 'Empréstimo Conta Garantida', 'passivo', TRUE),
  (915, 'Antecipação de Recebíveis', 'passivo', TRUE),
  (940, 'Empréstimo Banco Unicred', 'passivo', TRUE),
  (941, '(-) Juros sobre financiamento a apropriar', 'passivo', TRUE),
  (942, 'Empréstimo Banco Aymoré', 'passivo', TRUE),
  (954, 'Desenvolve -SP - Fungetur- Giro', 'passivo', TRUE),
  (1098, 'Empréstimo Banco Sicred', 'passivo', TRUE),
  (1100, 'Programa de Acão Cultural', 'passivo', TRUE),
  (1101, 'Programa de Acão Cultural', 'passivo', TRUE),
  (1183, 'Duplicatas Descontadas - Curto prazo', 'passivo', TRUE),
  (1186, 'Empréstimo Banco Sicoob', 'passivo', TRUE),
  (1221, 'Empréstimos a pagar', 'passivo', TRUE),
  (156, 'EMPRÉSTIMOS DE PESSOAS LIGADAS', 'passivo', TRUE),
  (157, 'Emprestimo de coligadas', 'passivo', TRUE),
  (765, 'EMPRÉSTIMOS DE SÓCIOS', 'passivo', TRUE),
  (709, 'Empréstimos de Sócios', 'passivo', TRUE),
  (1222, 'MÚTUOS COM TERCEIROS', 'passivo', TRUE),
  (1223, 'Mútuos com terceiros', 'passivo', TRUE),
  (158, 'OBRIGAÇÕES TRABALHISTAS', 'passivo', TRUE),
  (159, 'FOLHA DE PAGAMENTO DE EMPREGADOS', 'passivo', TRUE),
  (160, 'Salários a pagar', 'passivo', TRUE),
  (161, 'Férias a pagar', 'passivo', TRUE),
  (162, 'Rescisões a pagar', 'passivo', TRUE),
  (163, '13º salário a pagar', 'passivo', TRUE),
  (164, 'Participação lucros e resultados a pagar', 'passivo', TRUE),
  (165, 'Pensão alimentícia', 'passivo', TRUE),
  (999, 'Bônus a pagar', 'passivo', TRUE),
  (1302, 'Empréstimo Consignado a Recolher', 'passivo', TRUE),
  (1360, 'Penhora Judicial a Recolher', 'passivo', TRUE),
  (166, 'FOLHA DE PAGAMENTO DE AUTÔNOMOS', 'passivo', TRUE),
  (167, 'Rendimentos Autônomos a Pagar', 'passivo', TRUE),
  (168, 'FOLHA DE PAGAMENTO DE DIRIGENTES', 'passivo', TRUE),
  (169, 'Pro-labore a pagar', 'passivo', TRUE),
  (170, 'ENCARGOS FOLHA DE PAGAMENTO A PAGAR', 'passivo', TRUE),
  (171, 'INSS a pagar', 'passivo', TRUE),
  (172, 'FGTS a pagar', 'passivo', TRUE),
  (173, 'Contribuições Sindicais a Pagar', 'passivo', TRUE),
  (174, 'GRRF a Pagar', 'passivo', TRUE),
  (187, 'IRRF a pagar - Contribuintes', 'passivo', TRUE),
  (184, 'IRRF a pagar - Pessoa Física', 'passivo', TRUE),
  (1075, 'Contribuição Assistencial a Pagar', 'passivo', TRUE),
  (1076, 'Contribuição Confederativa a Pagar', 'passivo', TRUE),
  (175, 'PROVISÕES DA FOLHA DE PAGAMENTO', 'passivo', TRUE),
  (176, 'Provisão de 13º salário', 'passivo', TRUE),
  (177, 'Provisão de férias', 'passivo', TRUE),
  (178, 'Provisão FGTS 13º', 'passivo', TRUE),
  (179, 'Provisão FGTS Férias', 'passivo', TRUE),
  (180, 'Provisão INSS 13º', 'passivo', TRUE),
  (181, 'Provisão INSS Férias', 'passivo', TRUE),
  (182, 'OBRIGAÇÕES TRIBUTÁRIAS', 'passivo', TRUE),
  (183, 'IMPOSTOS RETIDOS A RECOLHER', 'passivo', TRUE),
  (185, 'IRRF a pagar - Pessoa Jurídica', 'passivo', TRUE),
  (186, 'ISS Retido a pagar', 'passivo', TRUE),
  (188, 'IRRF a pagar - PLR', 'passivo', TRUE),
  (672, 'Pis, Cofins e CSLL a pagar', 'passivo', TRUE),
  (673, 'INSS retido na fonte a pagar', 'passivo', TRUE),
  (699, 'IRRF Retido Aluguel a pagar', 'passivo', TRUE),
  (746, 'IOF a pagar', 'passivo', TRUE),
  (747, 'TFE a pagar', 'passivo', TRUE),
  (790, 'CIDE a pagar', 'passivo', TRUE),
  (920, 'TRSS a pagar', 'passivo', TRUE),
  (1350, 'IRRF a pagar - Sócio Pessoa Física', 'passivo', TRUE),
  (189, 'IMPOSTOS E CONTRIBUIÇÕES SOBRE O LUCRO', 'passivo', TRUE),
  (190, 'IRPJ a Pagar', 'passivo', TRUE),
  (191, 'CSLL a Pagar', 'passivo', TRUE),
  (194, 'IMPOSTOS E CONTRIBUIÇÕES S/RECEITAS', 'passivo', TRUE),
  (195, 'ICMS a Pagar', 'passivo', TRUE),
  (196, 'COFINS a Pagar', 'passivo', TRUE),
  (197, 'PIS a Pagar', 'passivo', TRUE),
  (198, 'IPI a Pagar', 'passivo', TRUE),
  (200, 'Contribuição Previdenciaria s/ Receita a pagar', 'passivo', TRUE),
  (201, 'ISSQN a Pagar', 'passivo', TRUE),
  (202, 'SIMPLES NACIONAL a Pagar', 'passivo', TRUE),
  (203, 'ICMS ST a Pagar', 'passivo', TRUE),
  (748, 'IMPOSTOS E CONTRIBUIÇÕES PARCELAMENTO', 'passivo', TRUE),
  (749, 'IRPJ a pagar (Parcelamento)', 'passivo', TRUE),
  (750, 'CSLL a pagar (Parcelamento)', 'passivo', TRUE),
  (751, 'Pis a pagar (Parcelamento)', 'passivo', TRUE),
  (752, 'Cofins a pagar (Parcelamento)', 'passivo', TRUE),
  (753, 'ISS - Dívida Ativa a pagar', 'passivo', TRUE),
  (754, 'Impostos Federais - Parcelamento', 'passivo', TRUE),
  (755, 'IRRF - 0561 (Parcelamento)', 'passivo', TRUE),
  (756, 'Pis, Cofins, CSLL - 5952 (Parcelamento)', 'passivo', TRUE),
  (892, 'INSS a Pagar (Parcelamento)', 'passivo', TRUE),
  (896, 'ISS a Pagar (Parcelamento)', 'passivo', TRUE),
  (927, '(-) Encargos financeiros a Apropriar (Parcelamento)', 'passivo', TRUE),
  (932, 'Simples Nacional a Pagar (Parcelamento)', 'passivo', TRUE),
  (1000, 'PERT - Consolidado (Parcelamento)', 'passivo', TRUE),
  (1038, 'Parcelamento PPI', 'passivo', TRUE),
  (1039, 'Parcelamento PGFN - Consolidado', 'passivo', TRUE),
  (1042, 'IRPJ a pagar (Parcelamento 2)', 'passivo', TRUE),
  (793, 'IMPOSTOS SOBRE IMPORTAÇÃO', 'passivo', TRUE),
  (794, 'IRRF sobre importação a pagar', 'passivo', TRUE),
  (795, 'CSLL sobre importação a pagar', 'passivo', TRUE),
  (796, 'PIS sobre importação a pagar', 'passivo', TRUE),
  (797, 'COFINS sobre importação a pagar', 'passivo', TRUE),
  (798, 'ISS sobre importação a pagar', 'passivo', TRUE),
  (204, 'CONTAS A PAGAR', 'passivo', TRUE),
  (205, 'CONTAS A PAGAR', 'passivo', TRUE),
  (210, 'DEMAIS CONTAS A PAGAR', 'passivo', TRUE),
  (211, 'Seguros a Pagar', 'passivo', TRUE),
  (212, 'Assinatura de Periódicos a Pagar', 'passivo', TRUE),
  (213, 'Aluguel a Pagar', 'passivo', TRUE),
  (702, 'Cartão de Crédito a Pagar', 'passivo', TRUE),
  (757, 'Despesas a Reembolsar', 'passivo', TRUE),
  (792, 'Dividendos a pagar', 'passivo', TRUE),
  (1060, 'Cartão de Crédito a Pagar 2', 'passivo', TRUE),
  (1063, 'Devolução de Capital Social a Liquidar', 'passivo', TRUE),
  (1055, 'Despesas Reembolsáveis a Pagar', 'passivo', TRUE),
  (1056, 'Despesas Reembolsáveis a Pagar - Juju', 'passivo', TRUE),
  (1057, 'Despesas Reembolsáveis a Pagar - Fashion', 'passivo', TRUE),
  (1058, 'Despesas Reembolsáveis a Pagar - Guerreiros', 'passivo', TRUE),
  (1212, 'Despesas Reembolsáveis a Pagar', 'passivo', TRUE),
  (1322, 'Despesas Reembolsáveis a Pagar - Só Nós Dois', 'passivo', TRUE),
  (1123, 'Despesas Reembolsáveis a Pagar - Rodeio Rock', 'passivo', TRUE),
  (1124, 'Despesas Reembolsáveis a Pagar - Era uma vez', 'passivo', TRUE),
  (1228, 'IPTU a Pagar', 'passivo', TRUE),
  (1321, 'IPVA a Pagar', 'passivo', TRUE),
  (1354, 'Consórcio a pagar', 'passivo', TRUE),
  (1230, 'OUTRAS CONTAS A PAGAR', 'passivo', TRUE),
  (1231, 'Outras Contas a Pagar', 'passivo', TRUE),
  (214, 'OBRIGAÇÕES COM TERCEIROS', 'passivo', TRUE),
  (215, 'Créditos a Regularizar', 'passivo', TRUE),
  (889, 'Caução - Aluguel', 'passivo', TRUE),
  (950, 'Alvará Judicial - Repasse', 'passivo', TRUE),
  (1065, 'Depositos Judiciais', 'passivo', TRUE),
  (707, 'ADIANTAMENTO DE CLIENTES', 'passivo', TRUE),
  (216, 'Adiantamento de clientes', 'passivo', TRUE),
  (623, 'RECEITAS DIFERIDAS', 'passivo', TRUE),
  (192, 'Receitas de Serviços a Apropriar', 'passivo', TRUE),
  (624, 'Receitas de Aplicações Financeiras', 'passivo', TRUE),
  (625, 'Receita de Juros Ativos', 'passivo', TRUE),
  (626, 'Receita de Variações Cambiais', 'passivo', TRUE),
  (627, 'Receita com descontos obtidos', 'passivo', TRUE),
  (745, 'Juros a Apropriar sobre Mútuo', 'passivo', TRUE),
  (977, 'Outras Receitas a Apropriar', 'passivo', TRUE),
  (1084, 'Receita de Venda de imóvel a Apropriar', 'passivo', TRUE),
  (766, 'ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'passivo', TRUE),
  (767, 'Adiantamento Para Futuro Aumento de Capital', 'passivo', TRUE),
  (1129, 'ADIANTAMENTO DE TERCEIROS', 'passivo', TRUE),
  (1130, 'Adiantamento de Terceiros', 'passivo', TRUE),
  (1341, 'DISTRIBUIÇÃO DE LUCROS A PAGAR', 'passivo', TRUE),
  (1342, 'Distribuição de Lucros a Pagar', 'passivo', TRUE),
  (220, 'PASSIVO NÃO CIRCULANTE', 'passivo', TRUE),
  (221, 'EMPRÉSTIMOS E FINANCIAMENTOS', 'passivo', TRUE),
  (222, 'EMPRÉSTIMOS E FINANCIAMENTOS BANCÁRIOS', 'passivo', TRUE),
  (223, 'Banco do Brasil SA', 'passivo', TRUE),
  (224, 'Caixa Econômica Federal SA', 'passivo', TRUE),
  (806, 'RCI Brasil', 'passivo', TRUE),
  (807, '(-) Encargos sobre empréstimos a apropriar - LP', 'passivo', TRUE),
  (813, 'Empréstimo Bradesco - LP', 'passivo', TRUE),
  (879, 'Empréstimo Capital de Giro - LP', 'passivo', TRUE),
  (1001, 'Desenvolve SP - Fungetur - Giro - LP', 'passivo', TRUE),
  (1004, 'Empréstimo Banco Itaú Unibanco - LP', 'passivo', TRUE),
  (1022, 'Empréstimo Banco Aymoré - LP', 'passivo', TRUE),
  (1023, '(-) Juros sobre financiamento a apropriar - LP', 'passivo', TRUE),
  (1059, 'Empréstimo BNDES', 'passivo', TRUE),
  (1099, 'Empréstimo Banco Sicred - LP', 'passivo', TRUE),
  (1184, 'Duplicatas Descontadas - Longo prazo', 'passivo', TRUE),
  (1187, 'Empréstimo Banco Sicoob', 'passivo', TRUE),
  (1198, 'Empréstimo Conta Garantida', 'passivo', TRUE),
  (1291, 'Empréstimos a pagar', 'passivo', TRUE),
  (758, 'MÚTUOS COM TERCEIROS', 'passivo', TRUE),
  (764, 'Mútuos com Terceiros', 'passivo', TRUE),
  (912, 'EMPRÉSTIMOS DE PESSOAS LIGADAS', 'passivo', TRUE),
  (913, 'Empréstimo de coligadas', 'passivo', TRUE),
  (897, 'OBRIGAÇÕES TRIBUTÁRIAS', 'passivo', TRUE),
  (898, 'IMPOSTOS E CONTRIBUIÇÕES PARCELAMENTO', 'passivo', TRUE),
  (899, 'CSLL a pagar (Parcelamento)', 'passivo', TRUE),
  (900, 'Cofins a pagar (Parcelamento)', 'passivo', TRUE),
  (901, 'INSS a Pagar (Parcelamento)', 'passivo', TRUE),
  (902, 'IRPJ a pagar (Parcelamento)', 'passivo', TRUE),
  (903, 'IRRF - 0561 (Parcelamento)', 'passivo', TRUE),
  (904, 'ISS - Dívida Ativa a pagar', 'passivo', TRUE),
  (905, 'Impostos Federais - Parcelamento', 'passivo', TRUE),
  (906, 'Pis a pagar (Parcelamento)', 'passivo', TRUE),
  (907, 'Pis, Cofins, CSLL - 5952 (Parcelamento)', 'passivo', TRUE),
  (908, 'ISS a Pagar (Parcelamento)', 'passivo', TRUE),
  (933, 'Simples Nacional a Pagar (Parcelamento)', 'passivo', TRUE),
  (970, 'Refis IV (Parcelamento)', 'passivo', TRUE),
  (971, 'PERT - Consolidado (Parcelamento)', 'passivo', TRUE),
  (1014, '(-) Encargos Financeiros a Apropriar (Parcelamento)- LP', 'passivo', TRUE),
  (1040, 'Parcelamento PGFN - Consolidado', 'passivo', TRUE),
  (1041, 'Parcelamento PPI', 'passivo', TRUE),
  (1043, 'PAT Parcelamento', 'passivo', TRUE),
  (1044, 'IRPJ a pagar (Parcelamento 2)', 'passivo', TRUE),
  (1243, 'Simples Nacional a Pagar (Divida Ativa)', 'passivo', TRUE),
  (1061, 'ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'passivo', TRUE),
  (1070, 'ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'passivo', TRUE),
  (1062, 'Adiantamento Para Futuro Aumento de Capital', 'passivo', TRUE),
  (1071, 'CONTAS A PAGAR', 'passivo', TRUE),
  (1072, 'CONTAS A PAGAR', 'passivo', TRUE),
  (1073, 'Caução - Aluguel', 'passivo', TRUE),
  (1229, 'Outras Obrigações', 'passivo', TRUE),
  (1247, 'OUTRAS OBRIGAÇÕES', 'passivo', TRUE),
  (1248, 'CONTA CORRENTE ENTRE COLIGADAS', 'passivo', TRUE),
  (1249, 'Conta Corrente Entre Coligadas', 'passivo', TRUE),
  (1357, 'DISTRIBUIÇÃO DE LUCROS A PAGAR', 'passivo', TRUE),
  (1358, 'Distribuição de Lucros a Pagar', 'passivo', TRUE),
  (1347, 'ADIANTAMENTO DE CLIENTES', 'passivo', TRUE),
  (1348, 'ADIANTAMENTO DE CLIENTES', 'passivo', TRUE),
  (1349, 'Adiantamento de clientes', 'passivo', TRUE),
  (225, 'PATRIMÔNIO LÍQUIDO', 'passivo', TRUE),
  (226, 'CAPITAL', 'passivo', TRUE),
  (227, 'CAPITAL SOCIAL', 'passivo', TRUE),
  (228, 'Capital Social', 'passivo', TRUE),
  (229, '(-)Capital Social a Integralizar', 'passivo', TRUE),
  (1087, 'Capital Social', 'passivo', TRUE),
  (1088, 'Capital Social Osirius', 'passivo', TRUE),
  (1089, 'Capital Social R2EAC', 'passivo', TRUE),
  (1090, 'Capital Social Opta', 'passivo', TRUE),
  (1352, 'Quotas em Tesouraria', 'passivo', TRUE),
  (1025, 'ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL PL', 'passivo', TRUE),
  (1027, 'Adiantamento p/ Futuro Aumento de Capital PL', 'passivo', TRUE),
  (1121, 'ADIANTAMENTO P/ FUTURO AUMENTO DE CAPITAL PL P', 'passivo', TRUE),
  (1122, 'Adto p/Futuro Aumento de Capital PL P', 'passivo', TRUE),
  (230, 'RESERVAS', 'passivo', TRUE),
  (231, 'RESERVAS DE CAPITAL', 'passivo', TRUE),
  (232, 'Reservas de Capital', 'passivo', TRUE),
  (233, 'RESERVAS DE LUCROS', 'passivo', TRUE),
  (234, 'Reserva de Lucros', 'passivo', TRUE),
  (235, 'Reserva de Contingências', 'passivo', TRUE),
  (236, 'Reserva Legal', 'passivo', TRUE),
  (237, 'Reserva Estatutária', 'passivo', TRUE),
  (238, 'Reserva de Lucros para Expansão', 'passivo', TRUE),
  (239, 'Reserva de Incentivos Fiscais', 'passivo', TRUE),
  (1011, 'Resultado do Exercício não Passivel de Distruibuição', 'passivo', TRUE),
  (655, 'LUCROS DISTRIBUÍDOS', 'passivo', TRUE),
  (656, 'Lucros Distribuídos', 'passivo', TRUE),
  (1253, 'LUCROS DISTRIBUIDOS SÓCIOS EXECUTIVOS', 'passivo', TRUE),
  (1254, 'Lucros Distribuidos Sócios Executivos', 'passivo', TRUE),
  (1256, 'LUCROS DISTRIBUIDOS SÓCIOS QUOTISTAS', 'passivo', TRUE),
  (1257, 'Lucros Distribuidos Sócios Quotistas', 'passivo', TRUE),
  (240, 'AJUSTES DE AVALIAÇÃO PATRIMONIAL', 'passivo', TRUE),
  (241, 'AJUSTES DE AVALIAÇÃO PATRIMONIAL', 'passivo', TRUE),
  (242, 'Normas Internacionais de Contabilidade', 'passivo', TRUE),
  (243, '(-) Normas Internacionais de Contabilidade', 'passivo', TRUE),
  (244, 'Avaliação de Instrumentos Financeiros', 'passivo', TRUE),
  (245, '(-) Avaliação de Instrumentos Financeiros', 'passivo', TRUE),
  (246, 'Ajustes ao Valor de Mercado', 'passivo', TRUE),
  (247, '(-) Ajustes ao Valor de Mercado', 'passivo', TRUE),
  (1285, 'Ajustes de Avaliação Patrimonial', 'passivo', TRUE),
  (248, 'AÇÕES EM TESOURARIA', 'passivo', TRUE),
  (249, 'AÇÕES EM TESOURARIA', 'passivo', TRUE),
  (712, 'Ações em Tesouraria', 'passivo', TRUE),
  (710, 'LUCROS OU PREJUÍZOS ACUMULADOS', 'passivo', TRUE),
  (711, 'LUCROS OU PREJUÍZOS ACUMULADOS', 'passivo', TRUE),
  (250, 'Lucros Acumulados', 'passivo', TRUE),
  (251, 'Prejuízos Acumulados', 'passivo', TRUE),
  (254, 'Ajustes de Exercícios Anteriores', 'passivo', TRUE),
  (836, 'Prejuízos Fiscais Acumulados', 'passivo', TRUE),
  (252, 'RESULTADO DO EXERCÍCIO', 'passivo', TRUE),
  (253, 'Resultado do Exercício', 'passivo', TRUE),
  (887, 'Resultado Parcial do Exercício', 'passivo', TRUE),
  (255, 'CONTAS DE COMPENSAÇÃO', 'passivo', TRUE),
  (256, 'CONTAS DE COMPENSAÇÃO', 'passivo', TRUE),
  (257, 'CONTAS DE COMPENSAÇÃO', 'passivo', TRUE),
  (258, 'Contas de Compensação', 'passivo', TRUE),
  (259, 'RECEITAS', 'receita', TRUE),
  (260, 'RECEITAS OPERACIONAIS', 'receita', TRUE),
  (261, 'RECEITA BRUTA COM VENDAS E SERVIÇOS', 'receita', TRUE),
  (262, 'RECEITA COM VENDAS E LOCAÇÕES', 'receita', TRUE),
  (263, 'Vendas de Produtos', 'receita', TRUE),
  (264, 'Vendas Produtos Fabricação Própria a Prazo', 'receita', TRUE),
  (265, 'Vendas de Mercadorias', 'receita', TRUE),
  (266, 'Vendas de Imóveis Próprios', 'receita', TRUE),
  (614, 'Receitas de Aluguel', 'receita', TRUE),
  (1135, 'Revenda de Mercadorias', 'receita', TRUE),
  (1306, 'Receita de Venda de Participações Societárias', 'receita', TRUE),
  (267, 'RECEITAS COM SERVIÇOS', 'receita', TRUE),
  (268, 'Serviços Prestados', 'receita', TRUE),
  (269, 'Serviços de Industrialização', 'receita', TRUE),
  (270, 'Serviços Prestados - Mercado Interno', 'receita', TRUE),
  (271, 'Direitos Autorais', 'receita', TRUE),
  (622, 'Serviços Prestados - Mercado Externo', 'receita', TRUE),
  (1290, 'Provisão Receita de Serviços Prestados', 'receita', TRUE),
  (272, 'DEDUÇÕES DAS RECEITAS C/VENDAS E SERVIÇO', 'receita', TRUE),
  (273, 'DEVOLUÇÕES E ABATIMENTOS', 'receita', TRUE),
  (275, 'Abatimentos Concedidos', 'receita', TRUE),
  (952, 'Cancelamento de Serviços de Clientes', 'receita', TRUE),
  (276, 'IMPOSTOS S/VENDAS E SERVIÇOS', 'receita', TRUE),
  (277, 'ICMS sobre vendas', 'receita', TRUE),
  (278, 'PIS sobre vendas e serviços', 'receita', TRUE),
  (279, 'COFINS sobre vendas e serviços', 'receita', TRUE),
  (280, 'Contribuição social sobre vendas e serviços', 'receita', TRUE),
  (281, 'IPI sobre vendas e serviços', 'receita', TRUE),
  (283, 'ISSQN sobre serviços', 'receita', TRUE),
  (284, 'Simples Nacional sobre vendas e serviços', 'receita', TRUE),
  (285, 'IRPJ sobre vendas e serviços', 'receita', TRUE),
  (335, 'CUSTOS DOS SERVIÇOS', 'despesa', TRUE),
  (336, 'CUSTOS DOS SERVIÇOS PRESTADOS', 'despesa', TRUE),
  (409, 'CUSTOS DOS SERVIÇOS PRESTADOS', 'despesa', TRUE),
  (410, 'MATERIAIS CONSUMIDOS', 'despesa', TRUE),
  (414, 'Material de Consumo', 'despesa', TRUE),
  (415, 'Material de Expediente', 'despesa', TRUE),
  (653, 'Material Medico', 'despesa', TRUE),
  (363, 'Materiais Diversos', 'despesa', TRUE),
  (1134, 'Livros, Jornais e Revistas', 'despesa', TRUE),
  (416, 'CUSTO DA MÃO-DE-OBRA DIRETA', 'despesa', TRUE),
  (417, '13.Salário', 'despesa', TRUE),
  (418, 'Adicional Noturno', 'despesa', TRUE),
  (419, 'Aviso Prévio/Indenizações Trabalhistas', 'despesa', TRUE),
  (420, 'Contribuições Sindicais', 'despesa', TRUE),
  (421, 'FGTS', 'despesa', TRUE),
  (422, 'Férias', 'despesa', TRUE),
  (423, 'Gratificações', 'despesa', TRUE),
  (424, 'Honorários Serviços Autônomos', 'despesa', TRUE),
  (425, 'Horas Extras', 'despesa', TRUE),
  (426, 'INSS', 'despesa', TRUE),
  (427, 'Multa Rescisória FGTS', 'despesa', TRUE),
  (428, 'PIS S/ Folha', 'despesa', TRUE),
  (429, 'Salários', 'despesa', TRUE),
  (431, 'Vale Alimentação', 'despesa', TRUE),
  (432, 'Vale Transporte', 'despesa', TRUE),
  (631, 'Vale Refeição', 'despesa', TRUE),
  (665, 'Assistência Médica e Odonto', 'despesa', TRUE),
  (666, 'Participação Por Resultados', 'despesa', TRUE),
  (698, 'Seguro de Vida em Grupo', 'despesa', TRUE),
  (760, 'Estagiários', 'despesa', TRUE),
  (781, 'Outras Despesas com Pessoal', 'despesa', TRUE),
  (800, 'Ajuda de Custo', 'despesa', TRUE),
  (814, 'Comissõoes', 'despesa', TRUE),
  (1030, 'Pró-labore', 'despesa', TRUE),
  (1185, 'Contribuicao Assistencial', 'despesa', TRUE),
  (433, 'OUTROS CUSTOS DOS SERVIÇOS', 'despesa', TRUE),
  (434, 'Água e Esgoto', 'despesa', TRUE),
  (435, 'Aluguel de imóveis - Pessoa Jurídica', 'despesa', TRUE),
  (436, 'Bens não imobilizáveis de pequeno valor', 'despesa', TRUE),
  (437, 'Brindes', 'despesa', TRUE),
  (438, 'Combustíveis e Lubrificantes', 'despesa', TRUE),
  (439, 'Depreciações e Amortizações', 'despesa', TRUE),
  (440, 'Energia Elétrica', 'despesa', TRUE),
  (441, 'Fretes e entregas', 'despesa', TRUE),
  (442, 'Manutenção e Conservação', 'despesa', TRUE),
  (443, 'Material de Consumo', 'despesa', TRUE),
  (444, 'Material de Expediente', 'despesa', TRUE),
  (445, 'Material de Segurança', 'despesa', TRUE),
  (446, 'Serviços de Terceiros - Pessoa Física', 'despesa', TRUE),
  (448, 'Telefone', 'despesa', TRUE),
  (449, 'Viagens', 'despesa', TRUE),
  (450, 'Propaganda e Publicidade', 'despesa', TRUE),
  (451, 'Material de Limpeza', 'despesa', TRUE),
  (452, 'Dispêndios com Alimentação', 'despesa', TRUE),
  (430, 'Serviços de Consultores - Pessoa Jurídica', 'despesa', TRUE),
  (677, 'Serviços de Informática', 'despesa', TRUE),
  (703, 'Taxa de Administradora de Cartão ou Carteiras', 'despesa', TRUE),
  (782, 'Pedágio', 'despesa', TRUE),
  (783, 'Condução e Táxi', 'despesa', TRUE),
  (784, 'Lanches e Refeições', 'despesa', TRUE),
  (785, 'Estacionamento', 'despesa', TRUE),
  (852, 'Corpo Docente PJ', 'despesa', TRUE),
  (853, 'Corpo Docente PF', 'despesa', TRUE),
  (854, 'Escola Parceira', 'despesa', TRUE),
  (855, 'Gravações', 'despesa', TRUE),
  (856, 'Material Gráfico', 'despesa', TRUE),
  (857, 'Catering', 'despesa', TRUE),
  (858, 'Licença de Uso de Software', 'despesa', TRUE),
  (859, 'Manutenção de Software', 'despesa', TRUE),
  (864, 'Serviços Médicos - PJ', 'despesa', TRUE),
  (963, 'Serviços Assessoria em Informática - Importação', 'despesa', TRUE),
  (1069, 'Serviços de Cuidadores', 'despesa', TRUE),
  (1074, 'Serviços de Recreação', 'despesa', TRUE),
  (1083, 'Direito de Uso', 'despesa', TRUE),
  (1155, 'Feiras e Eventos', 'despesa', TRUE),
  (1156, 'Domínio', 'despesa', TRUE),
  (1268, 'Aluguel de Veiculos', 'despesa', TRUE),
  (1304, 'Aluguel de Equipamentos Médicos', 'despesa', TRUE),
  (1260, 'CUSTO COM SERVIÇOS TOMADOS', 'despesa', TRUE),
  (1261, 'Serviços de Assessoria ou Consultoria', 'despesa', TRUE),
  (1262, 'Serviços de Apoio Administrativo', 'despesa', TRUE),
  (1263, 'Serviços de Cursos e Treinamentos', 'despesa', TRUE),
  (1264, 'Serviços de Fotografia', 'despesa', TRUE),
  (1269, 'Serviços de Assessoria em Informática', 'despesa', TRUE),
  (1270, 'Serviços de Organização de Feiras e Eventos', 'despesa', TRUE),
  (1271, 'Serviços de Comunicação', 'despesa', TRUE),
  (1272, 'Serviços de Estacionamento e Pedagios', 'despesa', TRUE),
  (1273, 'Serviços de Advocacia', 'despesa', TRUE),
  (1274, 'Serviços de Propaganda e Publicidade', 'despesa', TRUE),
  (1275, 'Serviços Gráficos', 'despesa', TRUE),
  (453, 'DESPESAS OPERACIONAIS', 'despesa', TRUE),
  (454, 'DESPESAS ADMINISTRATIVAS', 'despesa', TRUE),
  (681, 'DESPESAS E ENCARGOS TRABALHISTAS', 'despesa', TRUE),
  (455, 'DESPESAS TRABALHISTAS', 'despesa', TRUE),
  (456, 'Salários', 'despesa', TRUE),
  (457, 'Pró-Labore', 'despesa', TRUE),
  (458, 'Horas extras', 'despesa', TRUE),
  (459, 'Férias', 'despesa', TRUE),
  (460, '13.Salário', 'despesa', TRUE),
  (461, 'Aviso prévio/indenizações trabalhistas', 'despesa', TRUE),
  (462, 'Gratificações', 'despesa', TRUE),
  (463, 'Adicional noturno', 'despesa', TRUE),
  (464, 'Sindicato patronal/associação de classe', 'despesa', TRUE),
  (465, 'Vale-transporte', 'despesa', TRUE),
  (387, 'PIS S/ Folha', 'despesa', TRUE),
  (667, 'Participação Por Resultados', 'despesa', TRUE),
  (678, 'Vale Refeição', 'despesa', TRUE),
  (679, 'Vale Alimentação', 'despesa', TRUE),
  (492, 'PAT - Programa alimentação ao trabalhador', 'despesa', TRUE),
  (486, 'Assistência Médica e Odonto', 'despesa', TRUE),
  (704, 'Seguro de Vida em Grupo', 'despesa', TRUE),
  (761, 'Estagiários', 'despesa', TRUE),
  (788, 'Outras despesas com Pessoal', 'despesa', TRUE),
  (801, 'Ajuda de Custo', 'despesa', TRUE),
  (914, 'Cesta Básica', 'despesa', TRUE),
  (1096, 'Comissões', 'despesa', TRUE),
  (1125, 'Vale farmácia', 'despesa', TRUE),
  (1165, 'Honorários Serviços Autônomos', 'despesa', TRUE),
  (1192, 'Uniformes', 'despesa', TRUE),
  (466, 'ENCARGOS SOCIAIS', 'despesa', TRUE),
  (467, 'INSS', 'despesa', TRUE),
  (468, 'FGTS', 'despesa', TRUE),
  (469, 'Multa rescisória FGTS', 'despesa', TRUE),
  (470, 'PIS sobre folha', 'despesa', TRUE),
  (471, 'Contribuições Sindicais', 'despesa', TRUE),
  (1175, 'Contribuições Assistenciais', 'despesa', TRUE),
  (472, 'DESPESAS GERAIS', 'despesa', TRUE),
  (682, 'DESPESAS GERAIS', 'despesa', TRUE),
  (473, 'Aluguel de imóveis - Pessoa Jurídica', 'despesa', TRUE),
  (648, 'Aluguel de imóveis - Pessoa Fisica', 'despesa', TRUE),
  (475, 'Energia elétrica', 'despesa', TRUE),
  (523, 'Agua e Esgoto', 'despesa', TRUE),
  (529, 'Condominio', 'despesa', TRUE),
  (555, 'Telefone', 'despesa', TRUE),
  (476, 'Internet', 'despesa', TRUE),
  (478, 'Material de expediente', 'despesa', TRUE),
  (547, 'Material de Segurança', 'despesa', TRUE),
  (546, 'Material de higiêne', 'despesa', TRUE),
  (479, 'Material de limpeza', 'despesa', TRUE),
  (480, 'Material de escritório', 'despesa', TRUE),
  (503, 'Material de Consumo', 'despesa', TRUE),
  (477, 'Comissões sobre vendas', 'despesa', TRUE),
  (487, 'Associação de Classes', 'despesa', TRUE),
  (482, 'Correios e Malotes', 'despesa', TRUE),
  (485, 'Fretes e entregas', 'despesa', TRUE),
  (483, 'Depreciações e Amortizações', 'despesa', TRUE),
  (494, 'Livros, Jornais, Revistas e Assinatura de Boletins', 'despesa', TRUE),
  (495, 'Confraternizações', 'despesa', TRUE),
  (497, 'Seguros', 'despesa', TRUE),
  (498, 'Refeições', 'despesa', TRUE),
  (499, 'Viagens e Estadias', 'despesa', TRUE),
  (504, 'Copias e Autenticações', 'despesa', TRUE),
  (525, 'Bens não Imobilizáveis de Pequeno Valor', 'despesa', TRUE),
  (526, 'Brindes', 'despesa', TRUE),
  (527, 'Combustíveis e Lubrificantes', 'despesa', TRUE),
  (528, 'Comissões s/ Cartões de Crédito', 'despesa', TRUE),
  (533, 'Despesas com Transportes', 'despesa', TRUE),
  (536, 'Doações, Patrocinios e Contribuições', 'despesa', TRUE),
  (550, 'Royalties', 'despesa', TRUE),
  (696, 'Aluguel de Equipamentos', 'despesa', TRUE),
  (697, 'Aluguel de Veiculos', 'despesa', TRUE),
  (762, 'Copa e Cozinha', 'despesa', TRUE),
  (777, 'Manutenção de Veículos', 'despesa', TRUE),
  (786, 'Outras despesas administrativas', 'despesa', TRUE),
  (787, 'Outras taxas e impostos - Parcelamento', 'despesa', TRUE),
  (817, 'Domínio', 'despesa', TRUE),
  (842, 'Gás', 'despesa', TRUE),
  (843, 'TV por assinatura', 'despesa', TRUE),
  (883, 'Aluguel de Móveis', 'despesa', TRUE),
  (909, 'Hospedagem de Sites', 'despesa', TRUE),
  (934, 'Legais e Judiciais', 'despesa', TRUE),
  (943, 'Licença de Uso de Software', 'despesa', TRUE),
  (964, 'Quilometragem', 'despesa', TRUE),
  (1003, 'Condução e Táxi', 'despesa', TRUE),
  (1013, 'Manutenção, Reparos e Instalações', 'despesa', TRUE),
  (1028, 'Farmácia', 'despesa', TRUE),
  (1105, 'Feiras e Eventos', 'despesa', TRUE),
  (1107, 'Outras despesas de clientes', 'despesa', TRUE),
  (1240, 'Estacionamento', 'despesa', TRUE),
  (1241, 'Licença de Uso de Software - Importação', 'despesa', TRUE),
  (1242, 'Pedágio', 'despesa', TRUE),
  (1244, 'Aluguéis Diversos', 'despesa', TRUE),
  (1300, 'Flores, Folhagens e Plantas Ornamentais', 'despesa', TRUE),
  (1301, 'Impressão de Material Para Usos Diversos', 'despesa', TRUE),
  (1303, 'Licenciamento de Veículo', 'despesa', TRUE),
  (1305, 'Cursos e Treinamentos', 'despesa', TRUE),
  (1309, 'Despesas Com Apropriação Indébita', 'despesa', TRUE),
  (1351, 'Royalties - Exterior', 'despesa', TRUE),
  (700, 'DESPESAS GERAIS INDEDUTIVEIS', 'despesa', TRUE),
  (701, 'Despesas de Diretores', 'despesa', TRUE),
  (997, 'Outras Despesas Indedutiveis', 'despesa', TRUE),
  (350, 'DESPESAS COM SERVIÇOS TOMADOS', 'despesa', TRUE),
  (690, 'DESPESAS COM SERVIÇOS TOMADOS', 'despesa', TRUE),
  (481, 'Serviços de Manutenção e Conservação', 'despesa', TRUE),
  (488, 'Serviços de Terceiros - Pessoa Física', 'despesa', TRUE),
  (489, 'Serviços de Assessoria em Informática', 'despesa', TRUE),
  (490, 'Serviços de Organização de Feiras e Eventos', 'despesa', TRUE),
  (491, 'Serviços de Comunicação', 'despesa', TRUE),
  (502, 'Serviços de Estacionamento e Pedagios', 'despesa', TRUE),
  (615, 'Serviços de Assessoria ou Consultoria', 'despesa', TRUE),
  (616, 'Serviços de Advocacia', 'despesa', TRUE),
  (617, 'Serviços de Auditoria e Contabilidade', 'despesa', TRUE),
  (619, 'Serviços de Engenharia e Arquitetura', 'despesa', TRUE),
  (620, 'Serviços de Apoio Administrativo', 'despesa', TRUE),
  (632, 'Serviços de Recrutamento e Seleção', 'despesa', TRUE),
  (633, 'Serviços de Fornecimento de mão-de-obra', 'despesa', TRUE),
  (635, 'Serviços de Administração', 'despesa', TRUE),
  (636, 'Serviços de Cursos e Treinamentos', 'despesa', TRUE),
  (637, 'Serviços de Vigilância e Segurança', 'despesa', TRUE),
  (638, 'Serviços Artisticos e Musicais', 'despesa', TRUE),
  (641, 'Serviços de Limpeza', 'despesa', TRUE),
  (642, 'Serviços de Intermediação', 'despesa', TRUE),
  (643, 'Serviços de Representação Comercial', 'despesa', TRUE),
  (644, 'Serviços de Transporte', 'despesa', TRUE),
  (645, 'Serviços de Cartórios', 'despesa', TRUE),
  (646, 'Serviços Técnicos em Edificações e Telecomunicações', 'despesa', TRUE),
  (647, 'Serviços de Assessoria em Informática - Importação', 'despesa', TRUE),
  (484, 'Serviços de Propaganda e Publicidade', 'despesa', TRUE),
  (654, 'Serviços de Odontologia', 'despesa', TRUE),
  (556, 'Serviços de Pesquisa de Mercado e Congeneres', 'despesa', TRUE),
  (669, 'Serviços de Psicologia', 'despesa', TRUE),
  (670, 'Serviços de Ginastica', 'despesa', TRUE),
  (671, 'Serviços de Armazenagem', 'despesa', TRUE),
  (675, 'Serviços de Medicina Ocupacional', 'despesa', TRUE),
  (676, 'Serviços de Manutenção de Equipamentos', 'despesa', TRUE),
  (771, 'Serviços de Fotografia', 'despesa', TRUE),
  (772, 'Serviços Gráficos', 'despesa', TRUE),
  (773, 'Serviços de desenhos técnicos', 'despesa', TRUE),
  (774, 'Serviços de avaliação de bens e serviços', 'despesa', TRUE),
  (776, 'Serviços de Produção Audiovisual', 'despesa', TRUE),
  (791, 'Serviços de Pericias', 'despesa', TRUE),
  (799, 'Serviços de Cobranças', 'despesa', TRUE),
  (829, 'Serviços de Decoração e Jardinagem', 'despesa', TRUE),
  (832, 'Serviços de Demolição', 'despesa', TRUE),
  (833, 'Serviços de Direito de Uso de Espaço', 'despesa', TRUE),
  (834, 'Serviços de Assistência Técnica', 'despesa', TRUE),
  (835, 'Serviços de despachante', 'despesa', TRUE),
  (841, 'Serviços de meteorologia', 'despesa', TRUE),
  (876, 'Serviços de Reportagem e Assessoria de Imprensa', 'despesa', TRUE),
  (877, 'Serviços de Cuidados Pessoais', 'despesa', TRUE),
  (951, 'Serviços de Próteses sob encomenda', 'despesa', TRUE),
  (956, 'Serviços de Avaliação de Estatística', 'despesa', TRUE),
  (958, 'Serviços de Propaganda e Publicidade - Importação', 'despesa', TRUE),
  (969, 'Serviços de Nutrição', 'despesa', TRUE),
  (973, 'Serviços de Alfaiataria, Costura e Congeneres', 'despesa', TRUE),
  (974, 'Serviços de Criação de Obras de Arte', 'despesa', TRUE),
  (998, 'Serviços de Produção Audiovisual - Importação', 'despesa', TRUE),
  (1012, 'Serviços de Anúncios e Publicações', 'despesa', TRUE),
  (1106, 'Serviços de Assessoria ou Consultoria - Importação', 'despesa', TRUE),
  (1108, 'Serviços de análise técnica', 'despesa', TRUE),
  (1120, 'Serviços Farmacêuticos', 'despesa', TRUE),
  (1132, 'Serviços Artisticos e Musicais - Importação', 'despesa', TRUE),
  (1138, 'Serviços de Pesquisa de Mercado - Importação', 'despesa', TRUE),
  (1154, 'Serviços de Fonografia ou Gravação de Sons', 'despesa', TRUE),
  (1199, 'Serviços de estudos organizacionais', 'despesa', TRUE),
  (1281, 'Serviços de Colocação de molduras e congêneres.', 'despesa', TRUE),
  (1288, 'Serviços Médicos', 'despesa', TRUE),
  (1289, 'Serviços de Produção de Eventos', 'despesa', TRUE),
  (1310, 'Serviços de Advocacia – Importação', 'despesa', TRUE),
  (1326, 'Serviços de Escritório Virtual, Coworking e congêneres', 'despesa', TRUE),
  (569, 'DESPESAS OPERACIONAIS TRIBUTÁRIAS', 'despesa', TRUE),
  (570, 'IMPOSTOS', 'despesa', TRUE),
  (571, 'IOF', 'despesa', TRUE),
  (572, 'PIS sobre receitas operacionais diversas', 'despesa', TRUE),
  (573, 'IPTU', 'despesa', TRUE),
  (574, 'IPVA', 'despesa', TRUE),
  (575, 'IRRF (exclusivo Na Fonte)', 'despesa', TRUE),
  (576, 'Custas Leilão', 'despesa', TRUE),
  (577, 'Alvará de localização', 'despesa', TRUE),
  (578, 'ICMS', 'despesa', TRUE),
  (579, 'ICMS Diferencial de Aliquota', 'despesa', TRUE),
  (580, 'ICMS Substituição Tributária', 'despesa', TRUE),
  (581, 'ITR', 'despesa', TRUE),
  (582, 'Outras Taxas e Emolumentos', 'despesa', TRUE),
  (649, 'Pis s/ Importação', 'despesa', TRUE),
  (650, 'Cofins s/ Importação', 'despesa', TRUE),
  (651, 'IRRF s/ Importação', 'despesa', TRUE),
  (652, 'CIDE', 'despesa', TRUE),
  (691, 'Iss Retido na Fonte', 'despesa', TRUE),
  (759, 'Taxa de F. de Estabelecimentos - TFE', 'despesa', TRUE),
  (789, 'ISS s/ Importação', 'despesa', TRUE),
  (839, 'IRRF sobre aplicações financeiras', 'despesa', TRUE),
  (919, 'TRSS - Taxa de Resíduos Sólidos de Serviços de Saúde', 'despesa', TRUE),
  (937, 'ISS Uniprofissional', 'despesa', TRUE),
  (962, 'IRRF s/ Ganho de Capital', 'despesa', TRUE),
  (1194, 'PIS retido não recuperável', 'despesa', TRUE),
  (1195, 'COFINS retido não recuperável', 'despesa', TRUE),
  (686, 'PROVISÕES PARA PERDAS', 'despesa', TRUE),
  (687, 'PROVISÕES PARA PERDAS', 'despesa', TRUE),
  (589, 'PROVISÕES PARA PERDAS COM RECEBIVEIS', 'despesa', TRUE),
  (590, 'Prov. crédito de liquidação duvidosa', 'despesa', TRUE),
  (957, 'Prov. P/Perdas e Ajustes de Ativos', 'despesa', TRUE),
  (558, 'RESULTADO FINANCEIRO', 'despesa', TRUE),
  (559, 'RESULTADO FINANCEIRO', 'despesa', TRUE),
  (684, 'RESULTADOS COM ATUALIZAÇÕES', 'despesa', TRUE),
  (560, 'Variacão Monetária Passiva', 'despesa', TRUE),
  (561, 'Variacão Cambial Passiva', 'despesa', TRUE),
  (288, 'Variação Monetária Ativa', 'despesa', TRUE),
  (289, 'Variação Cambial Ativa', 'despesa', TRUE),
  (562, 'DESPESAS FINANCEIRAS', 'despesa', TRUE),
  (563, 'Juros', 'despesa', TRUE),
  (564, 'Descontos concedidos', 'despesa', TRUE),
  (565, 'Tarifa Bancárias', 'despesa', TRUE),
  (566, 'Despesas c/ factoring', 'despesa', TRUE),
  (567, 'Juros s/ Saldo Devedor C/C', 'despesa', TRUE),
  (568, 'Juros, Comissões s/ Financiamentos', 'despesa', TRUE),
  (763, 'Taxa Administradora de Cartões', 'despesa', TRUE),
  (838, 'Perdas em Aplicações Financeiras', 'despesa', TRUE),
  (884, 'Taxa Administração de Contas', 'despesa', TRUE),
  (286, 'RECEITAS FINANCEIRAS', 'despesa', TRUE),
  (291, 'NÃO USAR - Rendimentos de Aplicação do FAF', 'despesa', TRUE),
  (292, 'NÃO USAR - Ganho Real de Aplicações de Renda Fixa', 'despesa', TRUE),
  (293, 'Rendimento de Aplicações Financeiras', 'despesa', TRUE),
  (294, 'NÃO USAR - Rendimentos de Caderneta de Poupança', 'despesa', TRUE),
  (295, 'JUROS E DESCONTOS OBTIDOS', 'despesa', TRUE),
  (296, 'Juros Ativos', 'despesa', TRUE),
  (297, 'Descontos Obtidos', 'despesa', TRUE),
  (298, 'CORREÇÕES MONETÁRIAS DE BALANÇO', 'despesa', TRUE),
  (688, 'CORREÇÃO MONETÁRIA DO BALANCO', 'despesa', TRUE),
  (602, 'Correção Monetária do Ativo', 'despesa', TRUE),
  (603, 'Correção Monetária do Passivo', 'despesa', TRUE),
  (591, 'RESULTADOS C/PART. SOCIETARIAS E INVESTIMENTOS', 'despesa', TRUE),
  (595, 'RESULTADOS C/PART. SOCIETARIAS E INVESTIMENTOS', 'despesa', TRUE),
  (607, 'DIVIDENDOS E LUCROS RECEBIDOS', 'despesa', TRUE),
  (300, 'Dividendos Recebidos', 'despesa', TRUE),
  (685, 'DESPESAS EQUIVALÊNCIA PATRIOMONIAL', 'despesa', TRUE),
  (593, 'Despesas de Equivalência Patrimonial', 'despesa', TRUE),
  (302, 'RECEITAS DE EQUIVALÊNCIA PATRIMONIAL', 'despesa', TRUE),
  (303, 'Receita Equivalência Patrimonial', 'despesa', TRUE),
  (592, 'RESULTADO COM ATIVOS IMOBILIZADOS', 'despesa', TRUE),
  (315, 'ALIENAÇÃO DE IMOBILIZADO', 'despesa', TRUE),
  (316, 'Alienação de Máquinas e Equipamentos', 'despesa', TRUE),
  (317, 'Alienação de Móveis e Utensílios', 'despesa', TRUE),
  (318, 'Alienação de Ferramentas', 'despesa', TRUE),
  (319, 'Alienação de Imóveis', 'despesa', TRUE),
  (320, 'Alienação de Veículos', 'despesa', TRUE),
  (321, 'Alienação de Computadores e Periféricos', 'despesa', TRUE),
  (322, 'Alienação de Direito de Uso de Telefones', 'despesa', TRUE),
  (327, 'CUSTO DA ALIENAÇÃO DE IMOBILIZADO', 'despesa', TRUE),
  (328, 'Custo da Alienação Máquinas e Equipamentos', 'despesa', TRUE),
  (329, 'Custo da Alienação Móveis e Utensílios', 'despesa', TRUE),
  (330, 'Custo da Alienação Ferramentas', 'despesa', TRUE),
  (331, 'Custo da Alienação Imóveis', 'despesa', TRUE),
  (332, 'Custo da Alienação Veículos', 'despesa', TRUE),
  (333, 'Custo da Alienação Computadores e Periféricos', 'despesa', TRUE),
  (334, 'Custo da Alienação Direito Uso Telefone', 'despesa', TRUE),
  (594, 'PERDAS COM IMOBILIZADOS', 'despesa', TRUE),
  (597, 'Perdas com sinistros, roubo, deterioração', 'despesa', TRUE),
  (598, 'Perdas Na Alienação de Imobilizado', 'despesa', TRUE),
  (323, 'RESULTADO DAS ALIENAÇÕES DE PART. SOCIET.', 'despesa', TRUE),
  (312, 'ALIENAÇÃO DE INVESTIMENTOS', 'despesa', TRUE),
  (313, 'Alienação Participação Societária Avaliada pelo Metódo Custeio', 'despesa', TRUE),
  (314, 'Alienação Participação Societária Avaliada pela Equivalencia Patrimonial', 'despesa', TRUE),
  (1307, 'Alienação Participação Societária Avaliada pelo Valor de Mercado', 'despesa', TRUE),
  (324, 'CUSTO DA ALIENAÇÃO DE INVESTIMENTOS', 'despesa', TRUE),
  (325, 'Custo Alienação Partic Soc Aval Custo Co', 'despesa', TRUE),
  (326, 'Custo Alienação Partic Soc Aval Equiv Pa', 'despesa', TRUE),
  (299, 'PERDAS NAS ALIENAÇÕES DE PARTICIPAÇÕES', 'despesa', TRUE),
  (596, 'Perdas Na Alienação Investimento', 'despesa', TRUE),
  (304, 'OUTRAS DESPESAS E RECEITAS', 'despesa', TRUE),
  (305, 'OUTRAS DESPESAS E RECEITAS', 'despesa', TRUE),
  (306, 'OUTRAS RECEITAS', 'despesa', TRUE),
  (307, 'Bonificações', 'despesa', TRUE),
  (308, 'Doações', 'despesa', TRUE),
  (309, 'Benefício Fiscal', 'despesa', TRUE),
  (310, 'Despesas Recuperadas', 'despesa', TRUE),
  (311, 'Indenizações Trabalhistas', 'despesa', TRUE),
  (976, 'Outras receitas', 'despesa', TRUE),
  (1020, 'Receita de Juros s/Capital Próprio', 'despesa', TRUE),
  (1189, 'Indenização clientes', 'despesa', TRUE),
  (1355, 'Receita com Avaliação Patrimonial', 'despesa', TRUE),
  (583, 'MULTAS', 'despesa', TRUE),
  (584, 'Multas Fiscais Compensatórias', 'despesa', TRUE),
  (585, 'Multas Fiscais Punitivas', 'despesa', TRUE),
  (586, 'Multas Contratuais', 'despesa', TRUE),
  (587, 'Indenizações', 'despesa', TRUE),
  (588, 'Multas e Juros s/ Tributos', 'despesa', TRUE),
  (891, 'Multas de trânsito', 'despesa', TRUE),
  (894, 'Multas de Mora', 'despesa', TRUE),
  (1331, 'OUTRAS DESPESAS', 'despesa', TRUE),
  (1332, 'Perdas com Glosas', 'despesa', TRUE),
  (1353, 'Perdas com Créditos e Ajustes de Ativos', 'despesa', TRUE),
  (599, 'IMPOSTOS SOBRE O LUCRO', 'despesa', TRUE),
  (600, 'IMPOSTOS SOBRE O LUCRO', 'despesa', TRUE),
  (601, 'IMPOSTOS DE RENDA SOBRE O LUCRO', 'despesa', TRUE),
  (605, 'PROVISÕES P/IMPOSTOS S/LUCROS', 'despesa', TRUE),
  (606, 'Contribuição Social - CSLL', 'despesa', TRUE),
  (689, 'PROVISÕES P/IMPOSTOS S/LUCROS', 'despesa', TRUE),
  (604, 'PROVISÕES P/IMPOSTOS S/LUCROS', 'despesa', TRUE),
  (608, 'Imposto de Renda - IRPJ', 'despesa', TRUE),
  (609, 'RESULTADO LÍQUIDO DO EXERCÍCIO', 'outros', TRUE),
  (610, 'RESULTADO LIQUIDO DO EXERCICIO', 'outros', TRUE),
  (611, 'RESULTADO LIQUIDO DO EXERCICIO', 'outros', TRUE),
  (612, 'RESULTADO LIQUIDO DO EXERCICIO', 'outros', TRUE),
  (613, 'Resultado Líquido do Exercício', 'outros', TRUE);
INSERT INTO public.plano_contas (codigo, descricao, tipo, ativo) SELECT codigo::text, descricao, tipo, ativo FROM _pc;

-- 04 · colunas monetárias em lançamentos (UUID nos FKs)
-- MIGRATION · adicionar colunas monetarias em lancamentos
-- Necessario para conciliacao real e geracao de planilha SCI agregada
-- Opcao A do Code: adicionar à tabela existente (menos invasivo)
-- Gerado: 22/06/2026


-- Adiciona colunas se nao existirem
ALTER TABLE public.lancamentos
  ADD COLUMN IF NOT EXISTS conta_id UUID REFERENCES public.plano_contas(id),
  ADD COLUMN IF NOT EXISTS historico_id UUID REFERENCES public.historicos_contabeis(id),
  ADD COLUMN IF NOT EXISTS data_lancamento DATE,
  ADD COLUMN IF NOT EXISTS valor NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS descricao TEXT;

-- Indices para queries de agregacao
CREATE INDEX IF NOT EXISTS idx_lancamentos_conta ON public.lancamentos(conta_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_historico ON public.lancamentos(historico_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_data ON public.lancamentos(data_lancamento);


-- Verificacao:
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='lancamentos'
-- ORDER BY ordinal_position;
-- Deve incluir: conta_id, historico_id, data_lancamento, valor, descricao

-- 05 · ~203 lançamentos demo coerentes
-- LANCAMENTOS DEMO · ~200 lancamentos sinteticos coerentes
-- Para validacao da tela de conciliacao e geracao de planilha SCI
-- Cada empresa recebe 7 lancamentos com contas analiticas reais e historicos reais
-- Pre-requisito: 01, 02, 03, 04 ja rodados
-- Gerado: 22/06/2026


-- Apaga lancamentos demo anteriores (se houver)
DELETE FROM public.lancamentos WHERE descricao LIKE 'Lancamento demo · pre-validacao 23/06%';

-- Gera 7 lancamentos por empresa ativa
-- Usa contas analiticas (folhas, sem filhos) e historicos aleatorios
WITH analiticas AS (
  SELECT pc.id, pc.codigo, pc.descricao, pc.tipo
  FROM public.plano_contas pc
  WHERE NOT EXISTS (
    SELECT 1 FROM public.plano_contas pf WHERE pf.conta_pai_id = pc.id
  ) AND pc.ativo = TRUE
),
empresas_ativas AS (
  SELECT id FROM public.empresas WHERE ativo = TRUE AND is_demo = FALSE
)
INSERT INTO public.lancamentos (
  empresa_id, conta_id, historico_id, data_lancamento, valor, descricao,
  competencia, status
)
SELECT
  e.id AS empresa_id,
  (SELECT id FROM analiticas ORDER BY random() LIMIT 1) AS conta_id,
  (SELECT id FROM public.historicos_contabeis ORDER BY random() LIMIT 1) AS historico_id,
  (CURRENT_DATE - (random() * 30)::int) AS data_lancamento,
  ROUND((random() * 49900 + 100)::numeric, 2) AS valor,
  'Lancamento demo · pre-validacao 23/06 · linha ' || generate_series AS descricao,
  '2026-06' AS competencia,
  'gerada' AS status
FROM empresas_ativas e, generate_series(1, 7);


-- Verificacao:
-- SELECT COUNT(*) FROM lancamentos WHERE descricao LIKE 'Lancamento demo%';  -- ~203 (29 × 7)
-- SELECT e.nome_fantasia, COUNT(*) FROM lancamentos l JOIN empresas e ON e.id=l.empresa_id
--   WHERE l.descricao LIKE 'Lancamento demo%' GROUP BY e.nome_fantasia ORDER BY 1;
-- SELECT pc.descricao, SUM(l.valor) FROM lancamentos l JOIN plano_contas pc ON pc.id=l.conta_id
--   WHERE l.descricao LIKE 'Lancamento demo%' GROUP BY pc.descricao ORDER BY 2 DESC LIMIT 10;

COMMIT;
